// src/features/solicitacao-operacao/screens/detail-tabs/HistoricoTab.vue
<script setup lang="ts">
import { Clock } from 'lucide-vue-next';
import { detalheSolicitacao } from '../../data/operacaoData';
import { Section } from './shared';

defineProps<{ det: ReturnType<typeof detalheSolicitacao> }>();
</script>

<template>
  <Section title="Linha do Tempo">
    <div class="flex flex-col" style="position: relative">
      <div
        v-for="(ev, i) in det.historico"
        :key="i"
        class="flex items-start"
        style="gap: 16px; padding: 12px 0; position: relative"
      >
        <div style="position: relative; width: 12px">
          <span
            style="
              display: block;
              width: 12px;
              height: 12px;
              border-radius: 9999px;
              background: var(--gci-base);
              margin-top: 4px;
            "
          />
          <span
            v-if="i < det.historico.length - 1"
            style="
              position: absolute;
              left: 5px;
              top: 16px;
              bottom: -12px;
              width: 2px;
              background: var(--border-default);
            "
          />
        </div>
        <div style="flex: 1">
          <div style="font-size: var(--text-sm); font-weight: var(--weight-semibold); color: var(--text-strong)">
            <strong>{{ ev.autor }}</strong> {{ ev.acao }}
          </div>
          <div
            class="flex items-center"
            style="gap: 6px; font-size: var(--text-xs); color: var(--text-muted); margin-top: 2px"
          >
            <Clock :size="12" /> {{ ev.data }}
          </div>
        </div>
      </div>
    </div>
  </Section>
</template>

// src/features/solicitacao-operacao/screens/detail-tabs/HistoricoTab.tsx
import { Clock } from 'lucide-react';
import { detalheSolicitacao } from '../../data/operacaoData';
import { Section } from './shared';

export function HistoricoTab({ det }: { det: ReturnType<typeof detalheSolicitacao> }) {
  return (
    <Section title="Linha do Tempo">
      <div className="flex flex-col" style={{ position: 'relative' }}>
        {det.historico.map((ev, i) => (
          <div key={i} className="flex items-start" style={{ gap: 16, padding: '12px 0', position: 'relative' }}>
            <div style={{ position: 'relative', width: 12 }}>
              <span style={{ display: 'block', width: 12, height: 12, borderRadius: '9999px', background: 'var(--gci-base)', marginTop: 4 }} />
              {i < det.historico.length - 1 && <span style={{ position: 'absolute', left: 5, top: 16, bottom: -12, width: 2, background: 'var(--border-default)' }} />}
            </div>
            <div style={{ flex: 1 }}>
              <div style={{ fontSize: 'var(--text-sm)', fontWeight: 'var(--weight-semibold)', color: 'var(--text-strong)' }}>
                <strong>{ev.autor}</strong> {ev.acao}
              </div>
              <div className="flex items-center" style={{ gap: 6, fontSize: 'var(--text-xs)', color: 'var(--text-muted)', marginTop: 2 }}>
                <Clock size={12} /> {ev.data}
              </div>
            </div>
          </div>
        ))}
      </div>
    </Section>
  );
}
