// src/features/risco/screens/AgrupamentosScreen.tsx
import { useState } from 'react';
import { Plus, Layers, Pencil, Trash2 } from 'lucide-react';
import {
  AGRUPAMENTOS_SEED, OPERACOES_VINCULAVEIS_SEED, contarVinculos,
  type Agrupamento, type OperacaoVinculavel,
} from '../data/riscoData';
import { CreateAgrupamentoModal } from '../components/modals/CreateAgrupamentoModal';
import { DeleteAgrupamentoModal } from '../components/modals/DeleteAgrupamentoModal';
import { VincularAgrupamentoModal } from '../components/modals/VincularAgrupamentoModal';

const COLS = '2fr 0.8fr 0.8fr 0.8fr 1fr auto';

export function AgrupamentosScreen() {
  const [agrupamentos, setAgrupamentos] = useState<Agrupamento[]>(AGRUPAMENTOS_SEED);
  const [operacoes, setOperacoes] = useState<OperacaoVinculavel[]>(OPERACOES_VINCULAVEIS_SEED);
  const [creating, setCreating] = useState(false);
  const [editing, setEditing] = useState<Agrupamento | null>(null);
  const [deleting, setDeleting] = useState<Agrupamento | null>(null);
  const [vinculando, setVinculando] = useState<Agrupamento | null>(null);

  const handleCreate = (nome: string) => {
    setAgrupamentos((prev) => [
      ...prev,
      { id: `agp-${Date.now()}`, nome, cras: 0, fidcs: 0, criadoEm: new Date().toLocaleDateString('pt-BR') },
    ]);
    setCreating(false);
  };

  const handleRename = (nome: string) => {
    if (!editing) return;
    setAgrupamentos((prev) => prev.map((a) => (a.id === editing.id ? { ...a, nome } : a)));
    setEditing(null);
  };

  const handleDelete = () => {
    if (!deleting) return;
    setAgrupamentos((prev) => prev.filter((a) => a.id !== deleting.id));
    setDeleting(null);
  };

  return (
    <div className="flex flex-col" style={{ gap: 24 }}>
      {/* Identificação + ação primária */}
      <div className="flex items-center justify-between" style={{ gap: 16 }}>
        <div>
          <div style={{ fontSize: 11, textTransform: 'uppercase', letterSpacing: '0.18em', color: 'var(--accent)', fontWeight: 'var(--weight-bold)', marginBottom: 6 }}>
            Cadastro Global · Risco
          </div>
          <h1 style={{ fontSize: 26, fontWeight: 'var(--weight-bold)', color: 'var(--text-strong)', letterSpacing: '-0.02em', lineHeight: 1.15 }}>
            Agrupamentos de Limite
          </h1>
          <p style={{ fontSize: 'var(--text-sm)', color: 'var(--text-muted)', marginTop: 4 }}>
            {agrupamentos.length} {agrupamentos.length === 1 ? 'agrupamento cadastrado' : 'agrupamentos cadastrados'}
          </p>
        </div>
        <button
          onClick={() => setCreating(true)}
          className="flex items-center"
          style={{
            gap: 8, height: 48, padding: '0 22px',
            background: 'var(--agro-base)', color: '#fff',
            borderRadius: 'var(--radius-lg)', border: 'none', cursor: 'pointer',
            fontWeight: 'var(--weight-bold)', fontSize: 'var(--text-xs)', letterSpacing: '0.10em',
            boxShadow: '0 10px 24px -8px rgba(242,125,38,0.40)', transition: 'background var(--duration-base)',
          }}
          onMouseEnter={(e) => (e.currentTarget.style.background = 'var(--agro-hover)')}
          onMouseLeave={(e) => (e.currentTarget.style.background = 'var(--agro-base)')}
        >
          <span className="flex items-center justify-center" style={{ width: 22, height: 22, borderRadius: '9999px', background: 'rgba(255,255,255,0.20)' }}>
            <Plus size={14} />
          </span>
          NOVO AGRUPAMENTO
        </button>
      </div>

      {/* Tabela */}
      {agrupamentos.length === 0 ? (
        <EmptyState />
      ) : (
        <div style={{ border: '1px solid var(--border-default)', borderRadius: 'var(--radius-xl)', overflow: 'hidden', background: 'var(--surface-card)' }}>
          <div className="grid" style={{ gridTemplateColumns: COLS, padding: '12px 20px', background: 'var(--surface-sunken)', fontSize: 10, fontWeight: 'var(--weight-bold)', letterSpacing: '0.12em', color: 'var(--text-muted)', textTransform: 'uppercase' }}>
            <div>Agrupamento</div><div>CRAs</div><div>FIDCs</div><div>Total</div><div>Criado em</div><div style={{ textAlign: 'right' }}>Ações</div>
          </div>
          {agrupamentos.map((a) => {
            const { cras, fidcs, total } = contarVinculos(a.id, operacoes);
            return (
              <div
                key={a.id}
                onClick={() => setVinculando(a)}
                className="grid items-center"
                style={{ gridTemplateColumns: COLS, padding: '14px 20px', borderTop: '1px solid var(--border-default)', fontSize: 'var(--text-sm)', cursor: 'pointer', transition: 'background var(--duration-fast)' }}
                onMouseEnter={(e) => (e.currentTarget.style.background = 'var(--surface-sunken)')}
                onMouseLeave={(e) => (e.currentTarget.style.background = 'transparent')}
              >
                <div style={{ fontWeight: 'var(--weight-bold)', color: 'var(--text-strong)' }}>{a.nome}</div>
                <div style={{ fontVariantNumeric: 'tabular-nums', color: 'var(--text-default)' }}>{cras}</div>
                <div style={{ fontVariantNumeric: 'tabular-nums', color: 'var(--text-default)' }}>{fidcs}</div>
                <div style={{ fontVariantNumeric: 'tabular-nums', fontWeight: 'var(--weight-bold)', color: 'var(--text-strong)' }}>{total}</div>
                <div style={{ color: 'var(--text-muted)', fontVariantNumeric: 'tabular-nums' }}>{a.criadoEm}</div>
                <div className="flex items-center justify-end" style={{ gap: 8 }}>
                  <button
                    aria-label="Renomear agrupamento"
                    onClick={(e) => { e.stopPropagation(); setEditing(a); }}
                    className="flex items-center justify-center"
                    style={{ width: 32, height: 32, borderRadius: 'var(--radius-md)', background: 'none', border: '1px solid var(--border-default)', cursor: 'pointer', color: 'var(--text-muted)' }}
                  >
                    <Pencil size={14} />
                  </button>
                  <button
                    aria-label="Excluir agrupamento"
                    onClick={(e) => { e.stopPropagation(); setDeleting(a); }}
                    className="flex items-center justify-center"
                    style={{ width: 32, height: 32, borderRadius: 'var(--radius-md)', background: 'none', border: '1px solid var(--border-default)', cursor: 'pointer', color: 'var(--action-danger-text-only)' }}
                  >
                    <Trash2 size={14} />
                  </button>
                </div>
              </div>
            );
          })}
        </div>
      )}

      {creating && <CreateAgrupamentoModal onClose={() => setCreating(false)} onSave={handleCreate} />}
      {editing && <CreateAgrupamentoModal initial={editing} onClose={() => setEditing(null)} onSave={handleRename} />}
      {deleting && <DeleteAgrupamentoModal agrupamento={deleting} onClose={() => setDeleting(null)} onConfirm={handleDelete} />}
      {vinculando && (
        <VincularAgrupamentoModal
          agrupamento={vinculando}
          agrupamentos={agrupamentos}
          operacoes={operacoes}
          onUpdateOperacoes={setOperacoes}
          onClose={() => setVinculando(null)}
          onEdit={() => { setEditing(vinculando); setVinculando(null); }}
        />
      )}
    </div>
  );
}

function EmptyState() {
  return (
    <div className="flex flex-col items-center justify-center" style={{ gap: 10, padding: '48px 24px', textAlign: 'center', background: 'var(--surface-sunken)', borderRadius: 'var(--radius-lg)', border: '1px dashed var(--border-default)' }}>
      <Layers size={30} strokeWidth={1.5} style={{ color: 'var(--text-muted)', opacity: 0.5 }} />
      <div style={{ fontSize: 'var(--text-sm)', fontWeight: 'var(--weight-semibold)', color: 'var(--text-default)' }}>Nenhum agrupamento cadastrado</div>
      <div style={{ fontSize: 'var(--text-xs)', color: 'var(--text-muted)', maxWidth: 360 }}>Use "Novo agrupamento" para cadastrar o primeiro agrupamento de limite.</div>
    </div>
  );
}

// src/features/risco/screens/AgrupamentosScreen.vue
<script setup lang="ts">
import { ref } from 'vue';
import { Plus, Layers, Pencil, Trash2 } from 'lucide-vue-next';
import {
  AGRUPAMENTOS_SEED, OPERACOES_VINCULAVEIS_SEED, contarVinculos,
  type Agrupamento, type OperacaoVinculavel,
} from '../data/riscoData';
import CreateAgrupamentoModal from '../components/modals/CreateAgrupamentoModal.vue';
import DeleteAgrupamentoModal from '../components/modals/DeleteAgrupamentoModal.vue';
import VincularAgrupamentoModal from '../components/modals/VincularAgrupamentoModal.vue';

const COLS = '2fr 0.8fr 0.8fr 0.8fr 1fr auto';

const agrupamentos = ref<Agrupamento[]>(AGRUPAMENTOS_SEED);
const operacoes = ref<OperacaoVinculavel[]>(OPERACOES_VINCULAVEIS_SEED);
const creating = ref(false);
const editing = ref<Agrupamento | null>(null);
const deleting = ref<Agrupamento | null>(null);
const vinculando = ref<Agrupamento | null>(null);

function handleCreate(nome: string) {
  agrupamentos.value = [
    ...agrupamentos.value,
    { id: `agp-${Date.now()}`, nome, criadoEm: new Date().toLocaleDateString('pt-BR') },
  ];
  creating.value = false;
}

function handleRename(nome: string) {
  if (!editing.value) return;
  agrupamentos.value = agrupamentos.value.map((a) => (a.id === editing.value!.id ? { ...a, nome } : a));
  editing.value = null;
}

function handleDelete() {
  if (!deleting.value) return;
  agrupamentos.value = agrupamentos.value.filter((a) => a.id !== deleting.value!.id);
  deleting.value = null;
}
</script>

<template>
  <div class="flex flex-col" style="gap: 24px">
    <!-- Identificação + ação primária -->
    <div class="flex items-center justify-between" style="gap: 16px">
      <div>
        <div style="font-size: 11px; text-transform: uppercase; letter-spacing: 0.18em; color: var(--accent); font-weight: var(--weight-bold); margin-bottom: 6px">
          Cadastro Global · Risco
        </div>
        <h1 style="font-size: 26px; font-weight: var(--weight-bold); color: var(--text-strong); letter-spacing: -0.02em; line-height: 1.15">
          Agrupamentos de Limite
        </h1>
        <p style="font-size: var(--text-sm); color: var(--text-muted); margin-top: 4px">
          {{ agrupamentos.length }} {{ agrupamentos.length === 1 ? 'agrupamento cadastrado' : 'agrupamentos cadastrados' }}
        </p>
      </div>
      <button class="flex items-center risco-new-btn" style="gap: 8px; height: 48px; padding: 0 22px; color: #fff; border-radius: var(--radius-lg); border: none; cursor: pointer; font-weight: var(--weight-bold); font-size: var(--text-xs); letter-spacing: 0.10em; box-shadow: 0 10px 24px -8px rgba(242,125,38,0.40); transition: background var(--duration-base)" @click="creating = true">
        <span class="flex items-center justify-center" style="width: 22px; height: 22px; border-radius: 9999px; background: rgba(255,255,255,0.20)">
          <Plus :size="14" />
        </span>
        NOVO AGRUPAMENTO
      </button>
    </div>

    <!-- Tabela -->
    <div v-if="agrupamentos.length === 0" class="flex flex-col items-center justify-center" style="gap: 10px; padding: 48px 24px; text-align: center; background: var(--surface-sunken); border-radius: var(--radius-lg); border: 1px dashed var(--border-default)">
      <Layers :size="30" :stroke-width="1.5" style="color: var(--text-muted); opacity: 0.5" />
      <div style="font-size: var(--text-sm); font-weight: var(--weight-semibold); color: var(--text-default)">Nenhum agrupamento cadastrado</div>
      <div style="font-size: var(--text-xs); color: var(--text-muted); max-width: 360px">Use "Novo agrupamento" para cadastrar o primeiro agrupamento de limite.</div>
    </div>
    <div v-else style="border: 1px solid var(--border-default); border-radius: var(--radius-xl); overflow: hidden; background: var(--surface-card)">
      <div class="grid" :style="{ gridTemplateColumns: COLS, padding: '12px 20px', background: 'var(--surface-sunken)', fontSize: '10px', fontWeight: 'var(--weight-bold)', letterSpacing: '0.12em', color: 'var(--text-muted)', textTransform: 'uppercase' }">
        <div>Agrupamento</div><div>CRAs</div><div>FIDCs</div><div>Total</div><div>Criado em</div><div style="text-align: right">Ações</div>
      </div>
      <div
        v-for="a in agrupamentos"
        :key="a.id"
        class="grid items-center agrupamentos-row"
        :style="{ gridTemplateColumns: COLS, padding: '14px 20px', borderTop: '1px solid var(--border-default)', fontSize: 'var(--text-sm)', cursor: 'pointer', transition: 'background var(--duration-fast)' }"
        @click="vinculando = a"
      >
        <div style="font-weight: var(--weight-bold); color: var(--text-strong)">{{ a.nome }}</div>
        <div style="font-variant-numeric: tabular-nums; color: var(--text-default)">{{ contarVinculos(a.id, operacoes).cras }}</div>
        <div style="font-variant-numeric: tabular-nums; color: var(--text-default)">{{ contarVinculos(a.id, operacoes).fidcs }}</div>
        <div style="font-variant-numeric: tabular-nums; font-weight: var(--weight-bold); color: var(--text-strong)">{{ contarVinculos(a.id, operacoes).total }}</div>
        <div style="color: var(--text-muted); font-variant-numeric: tabular-nums">{{ a.criadoEm }}</div>
        <div class="flex items-center justify-end" style="gap: 8px">
          <button
            aria-label="Renomear agrupamento"
            class="flex items-center justify-center"
            style="width: 32px; height: 32px; border-radius: var(--radius-md); background: none; border: 1px solid var(--border-default); cursor: pointer; color: var(--text-muted)"
            @click.stop="editing = a"
          >
            <Pencil :size="14" />
          </button>
          <button
            aria-label="Excluir agrupamento"
            class="flex items-center justify-center"
            style="width: 32px; height: 32px; border-radius: var(--radius-md); background: none; border: 1px solid var(--border-default); cursor: pointer; color: var(--action-danger-text-only)"
            @click.stop="deleting = a"
          >
            <Trash2 :size="14" />
          </button>
        </div>
      </div>
    </div>

    <CreateAgrupamentoModal v-if="creating" @close="creating = false" @save="handleCreate" />
    <CreateAgrupamentoModal v-if="editing" :initial="editing" @close="editing = null" @save="handleRename" />
    <DeleteAgrupamentoModal v-if="deleting" :agrupamento="deleting" @close="deleting = null" @confirm="handleDelete" />
    <VincularAgrupamentoModal
      v-if="vinculando"
      :agrupamento="vinculando"
      :agrupamentos="agrupamentos"
      :operacoes="operacoes"
      @update:operacoes="operacoes = $event"
      @close="vinculando = null"
      @edit="() => { editing = vinculando; vinculando = null; }"
    />
  </div>
</template>

<style scoped>
.risco-new-btn {
  background: var(--agro-base);
}
.risco-new-btn:hover {
  background: var(--agro-hover);
}
.agrupamentos-row:hover {
  background: var(--surface-sunken);
}
</style>
