// src/features/fidc/components/modals/EditarParcelasModal.tsx
import { useState } from 'react';
import { X, Pencil, ChevronLeft, ChevronRight } from 'lucide-react';
import { brl, type ParcelaCronograma } from '../../data/fidcsData';

interface Props {
  cronograma: ParcelaCronograma[];
  onClose: () => void;
  onUpdate: (cronograma: ParcelaCronograma[]) => void;
}

export function EditarParcelasModal({ cronograma, onClose, onUpdate }: Props) {
  const [rows, setRows] = useState<ParcelaCronograma[]>(() => cronograma.map((c) => ({ ...c })));

  const setValor = (i: number, field: 'amortizacao' | 'juros', value: string) => {
    const num = Number(value.replace(',', '.')) || 0;
    setRows((prev) => prev.map((r, idx) => (idx === i ? { ...r, [field]: num } : r)));
  };

  const totalAmortizacao = rows.reduce((acc, r) => acc + r.amortizacao, 0);
  const totalJuros = rows.reduce((acc, r) => acc + r.juros, 0);
  const totalGeral = totalAmortizacao + totalJuros;

  return (
    <div
      style={{
        position: 'fixed', inset: 0,
        background: 'rgba(8,60,74,0.55)', backdropFilter: 'blur(8px)',
        zIndex: 500, display: 'flex', alignItems: 'center', justifyContent: 'center',
        padding: 32, animation: 'fadeIn 0.2s ease-out',
      }}
    >
      <div
        onClick={(e) => e.stopPropagation()}
        style={{
          background: 'var(--surface-card)', borderRadius: 'var(--radius-xl)',
          width: '100%', maxWidth: 900, maxHeight: '86vh',
          display: 'flex', flexDirection: 'column', overflow: 'hidden',
          boxShadow: 'var(--shadow-lg)',
        }}
      >
        {/* Header */}
        <div className="flex items-start justify-between" style={{ padding: '24px 32px', borderBottom: '1px solid var(--border-default)' }}>
          <div>
            <h2 style={{ fontSize: 'var(--text-2xl)', fontWeight: 'var(--weight-bold)', color: 'var(--text-strong)', letterSpacing: '-0.01em' }}>
              Editar Parcelas
            </h2>
            <p style={{ fontSize: 'var(--text-sm)', color: 'var(--text-muted)', marginTop: 4 }}>
              Ajuste os valores de amortização e juros de cada parcela do cronograma
            </p>
          </div>
          <button
            onClick={onClose}
            aria-label="Fechar"
            className="flex items-center justify-center"
            style={{ width: 36, height: 36, borderRadius: 'var(--radius-lg)', border: '1px solid var(--border-default)', background: 'var(--surface-card)', cursor: 'pointer', color: 'var(--text-muted)' }}
          >
            <X size={18} />
          </button>
        </div>

        {/* Body */}
        <div style={{ flex: 1, overflowY: 'auto', padding: 32 }}>
          <div style={{ border: '1px solid var(--border-default)', borderRadius: 'var(--radius-lg)', overflow: 'hidden' }}>
            <div className="grid" style={{ gridTemplateColumns: '1.2fr 1fr 1fr', padding: '10px 16px', background: 'var(--surface-sunken)', fontSize: 10, fontWeight: 'var(--weight-bold)', letterSpacing: '0.10em', color: 'var(--text-muted)', textTransform: 'uppercase' }}>
              <div>Vencimento</div><div>Amortização</div><div>Juros</div>
            </div>
            {rows.map((r, i) => (
              <div key={i} className="grid items-center" style={{ gridTemplateColumns: '1.2fr 1fr 1fr', padding: '10px 16px', borderTop: '1px solid var(--border-default)' }}>
                <div style={{ fontSize: 'var(--text-sm)', color: 'var(--text-muted)', fontVariantNumeric: 'tabular-nums' }}>{r.vencimento}</div>
                <EditableCell value={r.amortizacao} onChange={(v) => setValor(i, 'amortizacao', v)} />
                <EditableCell value={r.juros} onChange={(v) => setValor(i, 'juros', v)} />
              </div>
            ))}
            <div className="grid items-center" style={{ gridTemplateColumns: '1.2fr 1fr 1fr', padding: '12px 16px', borderTop: '1px solid var(--border-default)', background: 'var(--surface-sunken)', fontSize: 'var(--text-sm)', fontWeight: 'var(--weight-bold)', color: 'var(--text-strong)' }}>
              <div>Total</div>
              <div style={{ fontVariantNumeric: 'tabular-nums' }}>{brl(totalAmortizacao)}</div>
              <div style={{ fontVariantNumeric: 'tabular-nums' }}>{brl(totalJuros)}</div>
            </div>
          </div>

          {/* Paginação decorativa (não funcional) */}
          <div className="flex items-center justify-center" style={{ gap: 6, marginTop: 16 }}>
            <PageBtn icon={ChevronLeft} disabled />
            <span style={{ width: 30, height: 30, borderRadius: 'var(--radius-md)', background: 'var(--gci-base)', color: '#fff', fontSize: 'var(--text-xs)', fontWeight: 'var(--weight-bold)', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>1</span>
            <PageBtn icon={ChevronRight} disabled />
          </div>
        </div>

        {/* Footer */}
        <div className="flex items-center justify-between" style={{ padding: '16px 32px', borderTop: '1px solid var(--border-default)', background: 'var(--surface-card)' }}>
          <div style={{ fontSize: 'var(--text-xs)', fontWeight: 'var(--weight-bold)', letterSpacing: '0.08em', color: 'var(--text-muted)', textTransform: 'uppercase' }}>
            Valor Total: <span style={{ color: 'var(--text-strong)', fontVariantNumeric: 'tabular-nums' }}>{brl(totalGeral)}</span>
          </div>
          <div className="flex items-center" style={{ gap: 12 }}>
            <button
              onClick={onClose}
              style={{ height: 44, padding: '0 20px', background: 'none', border: 'none', cursor: 'pointer', color: 'var(--text-muted)', fontWeight: 'var(--weight-semibold)', fontSize: 'var(--text-sm)' }}
            >
              Cancelar
            </button>
            <button
              onClick={() => onUpdate(rows)}
              className="flex items-center"
              style={{ gap: 8, height: 44, padding: '0 24px', border: 'none', borderRadius: 'var(--radius-lg)', cursor: 'pointer', fontWeight: 'var(--weight-bold)', fontSize: 'var(--text-xs)', letterSpacing: '0.08em', background: 'var(--action-primary-bg)', color: '#fff' }}
            >
              <Pencil size={15} /> ATUALIZAR
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}

function EditableCell({ value, onChange }: { value: number; onChange: (v: string) => void }) {
  return (
    <input
      type="text"
      inputMode="decimal"
      defaultValue={value.toFixed(2)}
      onBlur={(e) => onChange(e.target.value)}
      style={{
        width: '100%', height: 36, padding: '0 12px',
        background: 'var(--surface-card)', border: '1px solid var(--border-default)',
        borderRadius: 'var(--radius-md)', outline: 'none',
        fontSize: 'var(--text-sm)', color: 'var(--text-strong)', fontVariantNumeric: 'tabular-nums',
      }}
    />
  );
}

function PageBtn({ icon: Icon, disabled }: { icon: typeof ChevronLeft; disabled?: boolean }) {
  return (
    <button
      disabled={disabled}
      className="flex items-center justify-center"
      style={{ width: 30, height: 30, borderRadius: 'var(--radius-md)', background: 'var(--surface-card)', border: '1px solid var(--border-default)', color: 'var(--text-disabled)', cursor: 'not-allowed' }}
    >
      <Icon size={14} />
    </button>
  );
}

// src/features/fidc/components/modals/EditarParcelasModal.vue
<script setup lang="ts">
import { ref, computed } from 'vue';
import { X, Pencil, ChevronLeft, ChevronRight } from 'lucide-vue-next';
import { brl, type ParcelaCronograma } from '../../data/fidcsData';
import EditableCell from './editar-parcelas/EditableCell.vue';
import PageBtn from './editar-parcelas/PageBtn.vue';

const props = defineProps<{ cronograma: ParcelaCronograma[] }>();
const emit = defineEmits<{ close: []; update: [cronograma: ParcelaCronograma[]] }>();

const rows = ref<ParcelaCronograma[]>(props.cronograma.map((c) => ({ ...c })));

function setValor(i: number, field: 'amortizacao' | 'juros', value: string) {
  const num = Number(value.replace(',', '.')) || 0;
  rows.value = rows.value.map((r, idx) => (idx === i ? { ...r, [field]: num } : r));
}

const totalAmortizacao = computed(() => rows.value.reduce((acc, r) => acc + r.amortizacao, 0));
const totalJuros = computed(() => rows.value.reduce((acc, r) => acc + r.juros, 0));
const totalGeral = computed(() => totalAmortizacao.value + totalJuros.value);
</script>

<template>
  <div
    style="
      position: fixed;
      inset: 0;
      background: rgba(8, 60, 74, 0.55);
      backdrop-filter: blur(8px);
      z-index: 500;
      display: flex;
      align-items: center;
      justify-content: center;
      padding: 32px;
      animation: fadeIn 0.2s ease-out;
    "
  >
    <div
      style="
        background: var(--surface-card);
        border-radius: var(--radius-xl);
        width: 100%;
        max-width: 900px;
        max-height: 86vh;
        display: flex;
        flex-direction: column;
        overflow: hidden;
        box-shadow: var(--shadow-lg);
      "
      @click.stop
    >
      <!-- Header -->
      <div class="flex items-start justify-between" style="padding: 24px 32px; border-bottom: 1px solid var(--border-default)">
        <div>
          <h2 style="font-size: var(--text-2xl); font-weight: var(--weight-bold); color: var(--text-strong); letter-spacing: -0.01em">
            Editar Parcelas
          </h2>
          <p style="font-size: var(--text-sm); color: var(--text-muted); margin-top: 4px">
            Ajuste os valores de amortização e juros de cada parcela do cronograma
          </p>
        </div>
        <button
          aria-label="Fechar"
          class="flex items-center justify-center"
          style="width: 36px; height: 36px; border-radius: var(--radius-lg); border: 1px solid var(--border-default); background: var(--surface-card); cursor: pointer; color: var(--text-muted)"
          @click="emit('close')"
        >
          <X :size="18" />
        </button>
      </div>

      <!-- Body -->
      <div style="flex: 1; overflow-y: auto; padding: 32px">
        <div style="border: 1px solid var(--border-default); border-radius: var(--radius-lg); overflow: hidden">
          <div class="grid" style="grid-template-columns: 1.2fr 1fr 1fr; padding: 10px 16px; background: var(--surface-sunken); font-size: 10px; font-weight: var(--weight-bold); letter-spacing: 0.10em; color: var(--text-muted); text-transform: uppercase">
            <div>Vencimento</div><div>Amortização</div><div>Juros</div>
          </div>
          <div
            v-for="(r, i) in rows"
            :key="i"
            class="grid items-center"
            style="grid-template-columns: 1.2fr 1fr 1fr; padding: 10px 16px; border-top: 1px solid var(--border-default)"
          >
            <div style="font-size: var(--text-sm); color: var(--text-muted); font-variant-numeric: tabular-nums">{{ r.vencimento }}</div>
            <EditableCell :value="r.amortizacao" @change="(v) => setValor(i, 'amortizacao', v)" />
            <EditableCell :value="r.juros" @change="(v) => setValor(i, 'juros', v)" />
          </div>
          <div class="grid items-center" style="grid-template-columns: 1.2fr 1fr 1fr; padding: 12px 16px; border-top: 1px solid var(--border-default); background: var(--surface-sunken); font-size: var(--text-sm); font-weight: var(--weight-bold); color: var(--text-strong)">
            <div>Total</div>
            <div style="font-variant-numeric: tabular-nums">{{ brl(totalAmortizacao) }}</div>
            <div style="font-variant-numeric: tabular-nums">{{ brl(totalJuros) }}</div>
          </div>
        </div>

        <!-- Paginação decorativa (não funcional) -->
        <div class="flex items-center justify-center" style="gap: 6px; margin-top: 16px">
          <PageBtn :icon="ChevronLeft" disabled />
          <span style="width: 30px; height: 30px; border-radius: var(--radius-md); background: var(--gci-base); color: #fff; font-size: var(--text-xs); font-weight: var(--weight-bold); display: flex; align-items: center; justify-content: center">1</span>
          <PageBtn :icon="ChevronRight" disabled />
        </div>
      </div>

      <!-- Footer -->
      <div class="flex items-center justify-between" style="padding: 16px 32px; border-top: 1px solid var(--border-default); background: var(--surface-card)">
        <div style="font-size: var(--text-xs); font-weight: var(--weight-bold); letter-spacing: 0.08em; color: var(--text-muted); text-transform: uppercase">
          Valor Total: <span style="color: var(--text-strong); font-variant-numeric: tabular-nums">{{ brl(totalGeral) }}</span>
        </div>
        <div class="flex items-center" style="gap: 12px">
          <button
            style="height: 44px; padding: 0 20px; background: none; border: none; cursor: pointer; color: var(--text-muted); font-weight: var(--weight-semibold); font-size: var(--text-sm)"
            @click="emit('close')"
          >
            Cancelar
          </button>
          <button
            class="flex items-center"
            style="gap: 8px; height: 44px; padding: 0 24px; border: none; border-radius: var(--radius-lg); cursor: pointer; font-weight: var(--weight-bold); font-size: var(--text-xs); letter-spacing: 0.08em; background: var(--action-primary-bg); color: #fff"
            @click="emit('update', rows)"
          >
            <Pencil :size="15" /> ATUALIZAR
          </button>
        </div>
      </div>
    </div>
  </div>
</template>
