// src/features/fidc/components/CreateFidcModal.vue
<script setup lang="ts">
import { ref, computed } from 'vue';
import type { Component } from 'vue';
import { X, Info, Mail, Check, ChevronRight, Phone, MapPin } from 'lucide-vue-next';
import StepGrid from './create-fidc/StepGrid.vue';
import SectionTitle from './create-fidc/SectionTitle.vue';
import FormField from './create-fidc/FormField.vue';
import SelectField from './create-fidc/SelectField.vue';

export interface NewFidcData {
  cnpj: string;
  identificacao: string;
  razaoSocial: string;
  nomeFantasia: string;
  dataConstituicao: string;
  naturezaLegal: string;
  atividadePrincipal: string;
  tipoEmpresa: string;
  tipoFundo: string;
  categoriaCvm: string;
  email: string;
  ddi: string;
  ddd: string;
  telefone: string;
  cep: string;
  endereco: string;
  numero: string;
  complemento: string;
  bairro: string;
  cidade: string;
  estado: string;
  pais: string;
}

const emit = defineEmits<{ close: []; create: [data: NewFidcData] }>();

interface Step {
  key: string;
  label: string;
  icon: Component;
  hint: string;
}

const steps: Step[] = [
  { key: 'info', label: 'Informações', icon: Info, hint: 'Dados cadastrais' },
  { key: 'contato', label: 'Contato', icon: Mail, hint: 'Contato & Endereço' },
];

const UF_OPTIONS = [
  'AC', 'AL', 'AP', 'AM', 'BA', 'CE', 'DF', 'ES', 'GO', 'MA',
  'MT', 'MS', 'MG', 'PA', 'PB', 'PR', 'PE', 'PI', 'RJ', 'RN',
  'RS', 'RO', 'RR', 'SC', 'SP', 'SE', 'TO',
];

const stepIdx = ref(0);
const hoverIdx = ref<number | null>(null);
const form = ref<NewFidcData>({
  cnpj: '',
  identificacao: '',
  razaoSocial: '',
  nomeFantasia: '',
  dataConstituicao: '',
  naturezaLegal: '',
  atividadePrincipal: '',
  tipoEmpresa: '',
  tipoFundo: '',
  categoriaCvm: '',
  email: '',
  ddi: '+55',
  ddd: '',
  telefone: '',
  cep: '',
  endereco: '',
  numero: '',
  complemento: '',
  bairro: '',
  cidade: '',
  estado: '',
  pais: 'Brasil',
});

const step = computed(() => steps[stepIdx.value]);
const isFirst = computed(() => stepIdx.value === 0);
const isLast = computed(() => stepIdx.value === steps.length - 1);

function stepColor(i: number) {
  const done = i < stepIdx.value;
  const current = i === stepIdx.value;
  return current ? 'var(--agro-base)' : done ? 'var(--gci-base)' : 'var(--text-muted)';
}

function stepDimmed(i: number) {
  const done = i < stepIdx.value;
  const current = i === stepIdx.value;
  return !current && !done && hoverIdx.value !== i ? 0.55 : 1;
}
</script>

<template>
  <div
    style="
      position: fixed;
      inset: 0;
      background: rgba(8, 60, 74, 0.55);
      backdrop-filter: blur(8px);
      z-index: 400;
      display: flex;
      align-items: center;
      justify-content: center;
      padding: 32px;
      animation: fadeIn 0.2s ease-out;
    "
    @click="emit('close')"
  >
    <div
      style="
        background: var(--surface-card);
        border-radius: var(--radius-xl);
        width: 100%;
        max-width: 900px;
        max-height: calc(100vh - 64px);
        display: flex;
        flex-direction: column;
        overflow: hidden;
        box-shadow: var(--shadow-lg);
      "
      @click.stop
    >
      <!-- Header -->
      <div class="flex items-start justify-between" style="padding: 24px 32px; border-bottom: 1px solid var(--border-default)">
        <div>
          <h2 style="font-size: var(--text-2xl); font-weight: 900; color: var(--text-strong); letter-spacing: -0.025em; line-height: 1.2; margin-bottom: 4px">
            Novo FIDC
          </h2>
          <p style="font-size: var(--text-sm); color: var(--text-muted)">
            {{ step.hint }} · Etapa {{ stepIdx + 1 }} de {{ steps.length }}
          </p>
        </div>
        <button aria-label="Fechar" class="flex items-center justify-center" style="width: 40px; height: 40px; border-radius: var(--radius-lg); background: var(--surface-sunken); border: none; cursor: pointer; color: var(--text-muted); flex-shrink: 0" @click="emit('close')">
          <X :size="18" />
        </button>
      </div>

      <!-- Stepper -->
      <div class="flex" style="background: var(--surface-sunken); border-bottom: 1px solid var(--border-default)">
        <button
          v-for="(s, i) in steps"
          :key="s.key"
          class="flex flex-col items-center justify-center"
          :style="{
            flex: 1,
            gap: '6px',
            padding: '14px 8px 11px',
            background: 'transparent',
            border: 'none',
            borderBottom: i === stepIdx ? '3px solid var(--agro-base)' : '3px solid transparent',
            cursor: 'pointer',
            color: stepColor(i),
            opacity: stepDimmed(i),
            transition: 'color var(--duration-base), opacity var(--duration-base), border-color var(--duration-base)',
          }"
          @click="stepIdx = i"
          @mouseenter="hoverIdx = i"
          @mouseleave="hoverIdx = null"
        >
          <component :is="s.icon" :size="18" :stroke-width="i === stepIdx ? 2.25 : 1.5" />
          <span style="font-size: 9px; font-weight: 800; letter-spacing: 0.20em; text-transform: uppercase; line-height: 1.2; white-space: nowrap">
            {{ s.label }}
          </span>
        </button>
      </div>

      <!-- Body -->
      <div style="flex: 1; overflow-y: auto; padding: 40px">
        <!-- Etapa 1 — Informações -->
        <StepGrid v-if="step.key === 'info'">
          <FormField label="CNPJ do Veículo" placeholder="00.000.000/0000-00" :span="4" v-model="form.cnpj" />
          <FormField label="Identificação do Veículo" placeholder="Ex: CERES AGRO I" :span="5" v-model="form.identificacao" />
          <SelectField label="Tipo de Empresa" :options="['Fundo', 'Companhia', 'Sociedade Limitada']" placeholder="Selecione" :span="3" v-model="form.tipoEmpresa" />

          <FormField label="Razão Social" placeholder="Razão social completa" :span="8" v-model="form.razaoSocial" />
          <FormField label="Nome Fantasia" placeholder="Ex: Ceres Agro I" :span="4" v-model="form.nomeFantasia" />

          <FormField label="Data de Constituição" type="date" :span="3" v-model="form.dataConstituicao" />
          <SelectField label="Natureza Legal" :options="['Condomínio Fechado', 'Condomínio Aberto', 'Sociedade Anônima']" placeholder="Selecione" :span="3" v-model="form.naturezaLegal" />
          <FormField label="Atividade Principal" placeholder="Direitos Creditórios" :span="6" v-model="form.atividadePrincipal" />

          <SelectField label="Tipo do Fundo" :options="['ABERTO', 'FECHADO']" placeholder="Selecione" :span="6" v-model="form.tipoFundo" />
          <SelectField label="Categoria CVM" :options="['FIDC', 'FIDC-NP', 'FIDC Agro']" placeholder="Selecione" :span="6" v-model="form.categoriaCvm" />
        </StepGrid>

        <!-- Etapa 2 — Contato & Endereço -->
        <div v-else-if="step.key === 'contato'" class="flex flex-col" style="gap: 20px">
          <div>
            <SectionTitle :icon="Phone">Contato</SectionTitle>
            <StepGrid>
              <FormField label="E-mail do Veículo" placeholder="contato@fidc.com.br" type="email" :span="6" v-model="form.email" />
              <FormField label="DDI" placeholder="+55" :span="2" v-model="form.ddi" />
              <FormField label="DDD" placeholder="11" :span="1" v-model="form.ddd" />
              <FormField label="Telefone" placeholder="0000-0000" :span="3" v-model="form.telefone" />
            </StepGrid>
          </div>
          <div>
            <SectionTitle :icon="MapPin">Endereço</SectionTitle>
            <StepGrid>
              <FormField label="CEP" placeholder="00000-000" :span="3" v-model="form.cep" />
              <FormField label="Endereço" placeholder="Av. Brigadeiro Faria Lima" :span="9" v-model="form.endereco" />
              <FormField label="Número" placeholder="—" :span="2" v-model="form.numero" />
              <FormField label="Complemento" placeholder="Sala 101" :span="4" v-model="form.complemento" />
              <FormField label="Bairro" placeholder="—" :span="6" v-model="form.bairro" />
              <FormField label="Cidade" placeholder="—" :span="5" v-model="form.cidade" />
              <SelectField label="Estado" :options="UF_OPTIONS" placeholder="UF" :span="3" v-model="form.estado" />
              <FormField label="País" placeholder="Brasil" :span="4" v-model="form.pais" />
            </StepGrid>
          </div>
        </div>
      </div>

      <!-- Footer -->
      <div class="flex items-center justify-between" style="padding: 16px 32px; border-top: 1px solid var(--border-default); background: var(--surface-card)">
        <button style="background: none; border: none; cursor: pointer; color: var(--text-muted); font-weight: 600; font-size: var(--text-sm); padding: 10px 4px" @click="isFirst ? emit('close') : stepIdx--">
          {{ isFirst ? 'Cancelar' : '← Voltar' }}
        </button>
        <span style="font-size: 11px; color: var(--text-muted); font-variant-numeric: tabular-nums">
          {{ stepIdx + 1 }} / {{ steps.length }}
        </span>
        <button
          class="flex items-center"
          :style="{
            gap: '8px',
            padding: '12px 28px',
            background: isLast ? 'var(--success-base)' : 'var(--action-primary-bg)',
            color: '#fff',
            border: 'none',
            borderRadius: 'var(--radius-lg)',
            cursor: 'pointer',
            fontWeight: 700,
            fontSize: 'var(--text-sm)',
            letterSpacing: '0.04em',
            boxShadow: isLast ? '0 8px 20px -8px rgba(5,150,105,0.40)' : '0 8px 20px -8px rgba(8,60,74,0.30)',
          }"
          @click="isLast ? emit('create', form) : stepIdx++"
        >
          {{ isLast ? 'Finalizar Cadastro' : 'Próxima Etapa' }}
          <Check v-if="isLast" :size="15" />
          <ChevronRight v-else :size="15" />
        </button>
      </div>
    </div>
  </div>
</template>

// src/features/fidc/components/CreateFidcModal.tsx
import { useState } from 'react';
import {
  X,
  Info,
  Mail,
  Check,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  Landmark,
  Phone,
  MapPin,
  type LucideIcon,
} from 'lucide-react';

export interface NewFidcData {
  cnpj: string;
  identificacao: string;
  razaoSocial: string;
  nomeFantasia: string;
  dataConstituicao: string;
  naturezaLegal: string;
  atividadePrincipal: string;
  tipoEmpresa: string;
  tipoFundo: string;
  categoriaCvm: string;
  email: string;
  ddi: string;
  ddd: string;
  telefone: string;
  cep: string;
  endereco: string;
  numero: string;
  complemento: string;
  bairro: string;
  cidade: string;
  estado: string;
  pais: string;
}

interface Props {
  onClose: () => void;
  onCreate: (data: NewFidcData) => void;
}

interface Step {
  key: string;
  label: string;
  icon: LucideIcon;
  hint: string;
}

const steps: Step[] = [
  { key: 'info',    label: 'Informações', icon: Info, hint: 'Dados cadastrais' },
  { key: 'contato', label: 'Contato',     icon: Mail, hint: 'Contato & Endereço' },
];

const UF_OPTIONS = [
  'AC','AL','AP','AM','BA','CE','DF','ES','GO','MA',
  'MT','MS','MG','PA','PB','PR','PE','PI','RJ','RN',
  'RS','RO','RR','SC','SP','SE','TO',
];

export function CreateFidcModal({ onClose, onCreate }: Props) {
  const [stepIdx, setStepIdx] = useState(0);
  const [form, setForm] = useState<NewFidcData>({
    cnpj: '',
    identificacao: '',
    razaoSocial: '',
    nomeFantasia: '',
    dataConstituicao: '',
    naturezaLegal: '',
    atividadePrincipal: '',
    tipoEmpresa: '',
    tipoFundo: '',
    categoriaCvm: '',
    email: '',
    ddi: '+55',
    ddd: '',
    telefone: '',
    cep: '',
    endereco: '',
    numero: '',
    complemento: '',
    bairro: '',
    cidade: '',
    estado: '',
    pais: 'Brasil',
  });

  const set = (field: keyof NewFidcData) =>
    (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>) =>
      setForm((prev) => ({ ...prev, [field]: e.target.value }));

  const setVal = (field: keyof NewFidcData) => (v: string) =>
    setForm((prev) => ({ ...prev, [field]: v }));

  const step = steps[stepIdx];
  const isFirst = stepIdx === 0;
  const isLast  = stepIdx === steps.length - 1;

  return (
    <div
      onClick={onClose}
      style={{
        position: 'fixed',
        inset: 0,
        background: 'rgba(8,60,74,0.55)',
        backdropFilter: 'blur(8px)',
        zIndex: 400,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        padding: 32,
        animation: 'fadeIn 0.2s ease-out',
      }}
    >
      <div
        onClick={(e) => e.stopPropagation()}
        style={{
          background: 'var(--surface-card)',
          borderRadius: 'var(--radius-xl)',
          width: '100%',
          maxWidth: 900,
          maxHeight: 'calc(100vh - 64px)',
          display: 'flex',
          flexDirection: 'column',
          overflow: 'hidden',
          boxShadow: 'var(--shadow-lg)',
        }}
      >
        {/* ── Header ── */}
        <div className="flex items-start justify-between" style={{ padding: '24px 32px', borderBottom: '1px solid var(--border-default)' }}>
          <div>
            <h2 style={{ fontSize: 'var(--text-2xl)', fontWeight: 900, color: 'var(--text-strong)', letterSpacing: '-0.025em', lineHeight: 1.2, marginBottom: 4 }}>
              Novo FIDC
            </h2>
            <p style={{ fontSize: 'var(--text-sm)', color: 'var(--text-muted)' }}>
              {step.hint} · Etapa {stepIdx + 1} de {steps.length}
            </p>
          </div>
          <button onClick={onClose} aria-label="Fechar" className="flex items-center justify-center" style={{ width: 40, height: 40, borderRadius: 'var(--radius-lg)', background: 'var(--surface-sunken)', border: 'none', cursor: 'pointer', color: 'var(--text-muted)', flexShrink: 0 }}>
            <X size={18} />
          </button>
        </div>

        {/* ── Stepper ── */}
        <div className="flex" style={{ background: 'var(--surface-sunken)', borderBottom: '1px solid var(--border-default)' }}>
          {steps.map((s, i) => {
            const Icon = s.icon;
            const done    = i < stepIdx;
            const current = i === stepIdx;
            const color = current ? 'var(--agro-base)' : done ? 'var(--gci-base)' : 'var(--text-muted)';
            return (
              <button key={s.key} onClick={() => setStepIdx(i)} className="flex flex-col items-center justify-center" style={{
                flex: 1, gap: 6, padding: '14px 8px 11px',
                background: 'transparent', border: 'none',
                borderBottom: current ? '3px solid var(--agro-base)' : '3px solid transparent',
                cursor: 'pointer', color,
                opacity: !current && !done ? 0.55 : 1,
                transition: 'color var(--duration-base), opacity var(--duration-base), border-color var(--duration-base)',
              }}
                onMouseEnter={(e) => { if (!current) e.currentTarget.style.opacity = '1'; }}
                onMouseLeave={(e) => { if (!current && !done) e.currentTarget.style.opacity = '0.55'; }}
              >
                <Icon size={18} strokeWidth={current ? 2.25 : 1.5} />
                <span style={{ fontSize: 9, fontWeight: 800, letterSpacing: '0.20em', textTransform: 'uppercase', lineHeight: 1.2, whiteSpace: 'nowrap' }}>
                  {s.label}
                </span>
              </button>
            );
          })}
        </div>

        {/* ── Body ── */}
        <div style={{ flex: 1, overflowY: 'auto', padding: 40 }}>

          {/* Etapa 1 — Informações */}
          {step.key === 'info' && (
            <StepGrid>
              {/* Row 1: CNPJ | Identificação | Tipo Empresa */}
              <FormField
                label="CNPJ do Veículo"
                placeholder="00.000.000/0000-00"
                span={4}
                value={form.cnpj}
                onChange={set('cnpj')}
              />
              <FormField
                label="Identificação do Veículo"
                placeholder="Ex: CERES AGRO I"
                span={5}
                value={form.identificacao}
                onChange={set('identificacao')}
              />
              <SelectField
                label="Tipo de Empresa"
                options={['Fundo', 'Companhia', 'Sociedade Limitada']}
                placeholder="Selecione"
                span={3}
                value={form.tipoEmpresa}
                onChange={setVal('tipoEmpresa')}
              />

              {/* Row 2: Razão Social | Nome Fantasia */}
              <FormField
                label="Razão Social"
                placeholder="Razão social completa"
                span={8}
                value={form.razaoSocial}
                onChange={set('razaoSocial')}
              />
              <FormField
                label="Nome Fantasia"
                placeholder="Ex: Ceres Agro I"
                span={4}
                value={form.nomeFantasia}
                onChange={set('nomeFantasia')}
              />

              {/* Row 3: Data Constituição | Natureza Legal | Atividade Principal */}
              <FormField
                label="Data de Constituição"
                type="date"
                span={3}
                value={form.dataConstituicao}
                onChange={set('dataConstituicao')}
              />
              <SelectField
                label="Natureza Legal"
                options={['Condomínio Fechado', 'Condomínio Aberto', 'Sociedade Anônima']}
                placeholder="Selecione"
                span={3}
                value={form.naturezaLegal}
                onChange={setVal('naturezaLegal')}
              />
              <FormField
                label="Atividade Principal"
                placeholder="Direitos Creditórios"
                span={6}
                value={form.atividadePrincipal}
                onChange={set('atividadePrincipal')}
              />

              {/* Row 4: Tipo do Fundo | Categoria CVM */}
              <SelectField
                label="Tipo do Fundo"
                options={['ABERTO', 'FECHADO']}
                placeholder="Selecione"
                span={6}
                value={form.tipoFundo}
                onChange={setVal('tipoFundo')}
              />
              <SelectField
                label="Categoria CVM"
                options={['FIDC', 'FIDC-NP', 'FIDC Agro']}
                placeholder="Selecione"
                span={6}
                value={form.categoriaCvm}
                onChange={setVal('categoriaCvm')}
              />
            </StepGrid>
          )}

          {/* Etapa 2 — Contato & Endereço */}
          {step.key === 'contato' && (
            <div className="flex flex-col" style={{ gap: 20 }}>
              <div>
                <SectionTitle icon={Phone}>Contato</SectionTitle>
                <StepGrid>
                  <FormField
                    label="E-mail do Veículo"
                    placeholder="contato@fidc.com.br"
                    type="email"
                    span={6}
                    value={form.email}
                    onChange={set('email')}
                  />
                  <FormField
                    label="DDI"
                    placeholder="+55"
                    span={2}
                    value={form.ddi}
                    onChange={set('ddi')}
                  />
                  <FormField
                    label="DDD"
                    placeholder="11"
                    span={1}
                    value={form.ddd}
                    onChange={set('ddd')}
                  />
                  <FormField
                    label="Telefone"
                    placeholder="0000-0000"
                    span={3}
                    value={form.telefone}
                    onChange={set('telefone')}
                  />
                </StepGrid>
              </div>
              <div>
                <SectionTitle icon={MapPin}>Endereço</SectionTitle>
                <StepGrid>
                  <FormField
                    label="CEP"
                    placeholder="00000-000"
                    span={3}
                    value={form.cep}
                    onChange={set('cep')}
                  />
                  <FormField
                    label="Endereço"
                    placeholder="Av. Brigadeiro Faria Lima"
                    span={9}
                    value={form.endereco}
                    onChange={set('endereco')}
                  />
                  <FormField
                    label="Número"
                    placeholder="—"
                    span={2}
                    value={form.numero}
                    onChange={set('numero')}
                  />
                  <FormField
                    label="Complemento"
                    placeholder="Sala 101"
                    span={4}
                    value={form.complemento}
                    onChange={set('complemento')}
                  />
                  <FormField
                    label="Bairro"
                    placeholder="—"
                    span={6}
                    value={form.bairro}
                    onChange={set('bairro')}
                  />
                  <FormField
                    label="Cidade"
                    placeholder="—"
                    span={5}
                    value={form.cidade}
                    onChange={set('cidade')}
                  />
                  <SelectField
                    label="Estado"
                    options={UF_OPTIONS}
                    placeholder="UF"
                    span={3}
                    value={form.estado}
                    onChange={setVal('estado')}
                  />
                  <FormField
                    label="País"
                    placeholder="Brasil"
                    span={4}
                    value={form.pais}
                    onChange={set('pais')}
                  />
                </StepGrid>
              </div>
            </div>
          )}
        </div>

        {/* ── Footer ── */}
        <div className="flex items-center justify-between" style={{ padding: '16px 32px', borderTop: '1px solid var(--border-default)', background: 'var(--surface-card)' }}>
          <button onClick={isFirst ? onClose : () => setStepIdx((i) => i - 1)} style={{ background: 'none', border: 'none', cursor: 'pointer', color: 'var(--text-muted)', fontWeight: 600, fontSize: 'var(--text-sm)', padding: '10px 4px' }}>
            {isFirst ? 'Cancelar' : '← Voltar'}
          </button>
          <span style={{ fontSize: 11, color: 'var(--text-muted)', fontVariantNumeric: 'tabular-nums' }}>
            {stepIdx + 1} / {steps.length}
          </span>
          <button onClick={isLast ? () => onCreate(form) : () => setStepIdx((i) => i + 1)} className="flex items-center" style={{
            gap: 8, padding: '12px 28px',
            background: isLast ? 'var(--success-base)' : 'var(--action-primary-bg)',
            color: '#fff', border: 'none', borderRadius: 'var(--radius-lg)', cursor: 'pointer',
            fontWeight: 700, fontSize: 'var(--text-sm)', letterSpacing: '0.04em',
            boxShadow: isLast ? '0 8px 20px -8px rgba(5,150,105,0.40)' : '0 8px 20px -8px rgba(8,60,74,0.30)',
          }}>
            {isLast ? 'Finalizar Cadastro' : 'Próxima Etapa'}
            {isLast ? <Check size={15} /> : <ChevronRight size={15} />}
          </button>
        </div>
      </div>
    </div>
  );
}

/* ─── Sub-components ─────────────────────────────────────────────── */

function StepGrid({ children }: { children: React.ReactNode }) {
  return (
    <div className="grid" style={{ gridTemplateColumns: 'repeat(12, 1fr)', gap: 16 }}>
      {children}
    </div>
  );
}

function SectionTitle({
  children,
  icon: Icon,
}: {
  children: React.ReactNode;
  icon?: LucideIcon;
}) {
  return (
    <div
      className="flex items-center"
      style={{
        gap: 8,
        fontSize: 10,
        fontWeight: 'var(--weight-bold)',
        letterSpacing: '0.18em',
        color: 'var(--accent)',
        textTransform: 'uppercase',
        marginTop: 8,
        marginBottom: 10,
      }}
    >
      {Icon && (
        <span
          className="flex items-center justify-center"
          style={{
            width: 24,
            height: 24,
            borderRadius: 'var(--radius-md)',
            background: 'var(--agro-light)',
            color: 'var(--agro-base)',
          }}
        >
          <Icon size={13} strokeWidth={2} />
        </span>
      )}
      {children}
    </div>
  );
}

function FieldLabel({ children }: { children: React.ReactNode }) {
  return (
    <div
      style={{
        fontSize: 10,
        fontWeight: 'var(--weight-bold)',
        letterSpacing: '0.14em',
        color: 'var(--text-muted)',
        textTransform: 'uppercase',
        marginBottom: 6,
      }}
    >
      {children}
    </div>
  );
}

function Input({
  disabled,
  style,
  ...rest
}: React.InputHTMLAttributes<HTMLInputElement>) {
  return (
    <input
      {...rest}
      disabled={disabled}
      style={{
        height: 40,
        padding: '0 14px',
        background: disabled ? 'var(--surface-sunken)' : 'var(--surface-card)',
        borderWidth: 1,
        borderStyle: 'solid',
        borderColor: 'var(--border-default)',
        borderRadius: 'var(--radius-md)',
        outline: 'none',
        fontSize: 'var(--text-sm)',
        color: disabled ? 'var(--text-muted)' : 'var(--text-strong)',
        width: '100%',
        ...style,
      }}
    />
  );
}

function FormField({
  label,
  placeholder,
  type,
  span,
  disabled,
  value,
  onChange,
}: {
  label: string;
  placeholder?: string;
  type?: string;
  span?: number;
  disabled?: boolean;
  value?: string;
  onChange?: React.ChangeEventHandler<HTMLInputElement>;
}) {
  return (
    <div style={{ gridColumn: span ? `span ${span}` : undefined }}>
      <FieldLabel>{label}</FieldLabel>
      <Input
        placeholder={placeholder}
        type={type}
        disabled={disabled}
        value={value}
        onChange={onChange}
      />
    </div>
  );
}

function SelectField({
  label,
  options,
  span,
  placeholder,
  value,
  onChange,
}: {
  label?: string;
  options: string[];
  span?: number;
  placeholder?: string;
  value?: string;
  onChange?: (v: string) => void;
}) {
  return (
    <div style={{ gridColumn: span ? `span ${span}` : undefined }}>
      {label && <FieldLabel>{label}</FieldLabel>}
      <div style={{ position: 'relative' }}>
        <select
          value={value}
          onChange={(e) => onChange?.(e.target.value)}
          style={{
            height: 40,
            paddingLeft: 14,
            paddingRight: 40,
            background: 'var(--surface-card)',
            borderWidth: 1,
            borderStyle: 'solid',
            borderColor: 'var(--border-default)',
            borderRadius: 'var(--radius-md)',
            outline: 'none',
            fontSize: 'var(--text-sm)',
            color: value ? 'var(--text-strong)' : 'var(--text-muted)',
            width: '100%',
            appearance: 'none',
            WebkitAppearance: 'none',
            MozAppearance: 'none',
          }}
        >
          {placeholder && (
            <option value="" disabled>
              {placeholder}
            </option>
          )}
          {options.map((o) => (
            <option key={o} value={o}>
              {o}
            </option>
          ))}
        </select>
        <ChevronDown
          size={16}
          style={{
            position: 'absolute',
            right: 14,
            top: '50%',
            transform: 'translateY(-50%)',
            color: 'var(--text-muted)',
            pointerEvents: 'none',
          }}
        />
      </div>
    </div>
  );
}
