// src/features/fidc/screens/TitleDetailScreen.tsx
import { useState } from 'react';
import {
  ArrowLeft,
  FileText,
  Paperclip,
  CreditCard,
  Activity,
  CheckCircle2,
  Clock,
  Download,
  Mail,
  Phone,
  Building2,
  User,
  TrendingUp,
  BadgeCheck,
  ArrowLeftRight,
  Copy,
  Check as CheckIcon,
} from 'lucide-react';
import { brl, detalhePagamentos, type Fidc, type FidcClass, type Title, type TitleStatus } from '../data/fidcsData';
import { PagamentosTab } from './detail-tabs/PagamentosTab';

interface Props {
  fidc: Fidc;
  klass: FidcClass;
  title: Title;
  onBack: () => void;
}

type Tab = 'detalhes' | 'anexos' | 'accrual' | 'pagamentos' | 'confirmacoes' | 'movimentacoes' | 'historico';

const statusTone: Record<TitleStatus, { bg: string; fg: string; iconBg: string }> = {
  CONFIRMADO: {
    bg: 'var(--success-light)',
    fg: 'var(--success-dark)',
    iconBg: 'var(--success-base)',
  },
  PENDENTE: {
    bg: 'var(--warning-light)',
    fg: 'var(--warning-dark)',
    iconBg: 'var(--warning-base)',
  },
  VENCIDO: {
    bg: 'var(--danger-light)',
    fg: 'var(--danger-dark)',
    iconBg: 'var(--danger-base)',
  },
};

export function TitleDetailScreen({ fidc, klass, title, onBack }: Props) {
  const [tab, setTab] = useState<Tab>('detalhes');
  const [det, setDet] = useState(() => detalhePagamentos(title));
  const tone = statusTone[title.status];

  return (
    <div className="flex flex-col" style={{ gap: 24 }}>
      {/* Header */}
      <div className="flex items-center" style={{ gap: 16 }}>
        <button
          onClick={onBack}
          aria-label="Voltar"
          className="flex items-center justify-center"
          style={{
            width: 48,
            height: 48,
            borderRadius: 'var(--radius-lg)',
            background: 'var(--surface-card)',
            borderWidth: 1,
            borderStyle: 'solid',
            borderColor: 'var(--border-default)',
            cursor: 'pointer',
            color: 'var(--text-strong)',
          }}
        >
          <ArrowLeft size={20} />
        </button>
        <div style={{ flex: 1 }}>
          <div
            style={{
              fontSize: 10,
              fontWeight: 'var(--weight-bold)',
              letterSpacing: '0.18em',
              color: 'var(--agro-base)',
              textTransform: 'uppercase',
              marginBottom: 4,
            }}
          >
            {fidc.name} • {klass.name}
          </div>
          <h2
            className="flex items-center"
            style={{
              fontSize: 'var(--text-xl)',
              fontWeight: 'var(--weight-bold)',
              color: 'var(--text-strong)',
              letterSpacing: '-0.01em',
              lineHeight: 1.2,
              gap: 8,
            }}
          >
            Título #{title.numero}
            <CopyButton value={`Título #${title.numero}`} />
          </h2>
          <p style={{ fontSize: 'var(--text-sm)', color: 'var(--text-muted)', marginTop: 4 }}>
            Auditoria e ciclo de vida do direito creditório
          </p>
        </div>
        <span
          className="flex items-center"
          style={{
            gap: 8,
            fontSize: 11,
            fontWeight: 'var(--weight-bold)',
            letterSpacing: '0.12em',
            padding: '8px 14px',
            background: tone.bg,
            color: tone.fg,
            borderRadius: '9999px',
          }}
        >
          {title.status === 'CONFIRMADO' ? (
            <CheckCircle2 size={14} />
          ) : (
            <Clock size={14} />
          )}
          {title.status}
        </span>
      </div>

      {/* Painel valor */}
      <div
        className="relative overflow-hidden flex items-center"
        style={{
          background: 'var(--gci-base)',
          borderRadius: 'var(--radius-xl)',
          padding: '28px 32px',
          color: '#fff',
          boxShadow: '0 20px 40px -20px rgba(8,60,74,0.40)',
        }}
      >
        <div
          style={{
            position: 'absolute',
            top: -100,
            right: -100,
            width: 320,
            height: 320,
            borderRadius: '9999px',
            background: 'rgba(255,255,255,0.04)',
          }}
        />
        <div style={{ flex: 1, position: 'relative', zIndex: 1 }}>
          <div
            style={{
              fontSize: 11,
              fontWeight: 'var(--weight-bold)',
              letterSpacing: '0.18em',
              color: 'var(--agro-base)',
              textTransform: 'uppercase',
              marginBottom: 10,
            }}
          >
            Valor Nominal do Título
          </div>
          <div
            style={{
              fontSize: 36,
              fontWeight: 'var(--weight-bold)',
              letterSpacing: '-0.02em',
              fontVariantNumeric: 'tabular-nums',
              lineHeight: 1.1,
            }}
          >
            {brl(title.vrNominal)}
          </div>
          <div
            style={{ fontSize: 'var(--text-xs)', color: 'rgba(255,255,255,0.65)', marginTop: 8 }}
          >
            Lastro: {title.lastro.replace('_', '-')} • Emissão {title.emissao} • Vencimento{' '}
            {title.vencimento}
          </div>
        </div>
      </div>

      {/* Tabs */}
      <div
        className="flex items-center"
        style={{
          gap: 4,
          padding: 4,
          background: 'var(--surface-card)',
          borderWidth: 1,
          borderStyle: 'solid',
          borderColor: 'var(--border-default)',
          borderRadius: 'var(--radius-xl)',
          alignSelf: 'flex-start',
        }}
      >
        <TabPill active={tab === 'detalhes'} onClick={() => setTab('detalhes')} icon={FileText}>Detalhes</TabPill>
        <TabPill active={tab === 'anexos'} onClick={() => setTab('anexos')} icon={Paperclip}>Anexos</TabPill>
        <TabPill active={tab === 'accrual'} onClick={() => setTab('accrual')} icon={TrendingUp}>Accrual</TabPill>
        <TabPill active={tab === 'pagamentos'} onClick={() => setTab('pagamentos')} icon={CreditCard}>Pagamentos</TabPill>
        <TabPill active={tab === 'confirmacoes'} onClick={() => setTab('confirmacoes')} icon={BadgeCheck}>Confirmações</TabPill>
        <TabPill active={tab === 'movimentacoes'} onClick={() => setTab('movimentacoes')} icon={ArrowLeftRight}>Movimentações</TabPill>
        <TabPill active={tab === 'historico'} onClick={() => setTab('historico')} icon={Activity}>Histórico</TabPill>
      </div>

      <div
        style={{
          background: 'var(--surface-card)',
          borderWidth: 1,
          borderStyle: 'solid',
          borderColor: 'var(--border-default)',
          borderRadius: 'var(--radius-xl)',
          padding: 24,
        }}
      >
        {tab === 'detalhes'      && <DetailsTab title={title} klass={klass} />}
        {tab === 'anexos'        && <AnexosTab title={title} />}
        {tab === 'accrual'       && <AccrualTab title={title} />}
        {tab === 'pagamentos'    && <PagamentosTab title={title} det={det} setDet={setDet} />}
        {tab === 'confirmacoes'  && <ConfirmacoesTab title={title} />}
        {tab === 'movimentacoes' && <MovimentacoesTab title={title} />}
        {tab === 'historico'     && <MovimentoTab title={title} />}
      </div>
    </div>
  );
}

function CopyButton({ value }: { value: string }) {
  const [copied, setCopied] = useState(false);
  const handleCopy = (e: React.MouseEvent) => {
    e.stopPropagation();
    navigator.clipboard.writeText(value).catch(() => {});
    setCopied(true);
    setTimeout(() => setCopied(false), 1500);
  };
  return (
    <button
      onClick={handleCopy}
      title={copied ? 'Copiado!' : 'Copiar'}
      style={{
        background: 'none',
        border: 'none',
        cursor: 'pointer',
        padding: 2,
        color: copied ? 'var(--success-base)' : 'var(--text-muted)',
        display: 'inline-flex',
        alignItems: 'center',
        borderRadius: 4,
        flexShrink: 0,
        transition: 'color var(--duration-fast)',
      }}
    >
      {copied ? <CheckIcon size={13} /> : <Copy size={13} />}
    </button>
  );
}

function TabPill({
  active,
  onClick,
  icon: Icon,
  children,
}: {
  active: boolean;
  onClick: () => void;
  icon: typeof FileText;
  children: React.ReactNode;
}) {
  return (
    <button
      onClick={onClick}
      className="flex items-center"
      style={{
        gap: 8,
        padding: '10px 16px',
        fontSize: 'var(--text-sm)',
        fontWeight: 'var(--weight-bold)',
        border: 'none',
        cursor: 'pointer',
        borderRadius: 'var(--radius-lg)',
        background: active ? 'var(--gci-base)' : 'transparent',
        color: active ? '#fff' : 'var(--text-muted)',
        transition: 'all var(--duration-base)',
      }}
    >
      <Icon size={14} />
      {children}
    </button>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div>
      <div
        style={{
          fontSize: 10,
          fontWeight: 'var(--weight-bold)',
          letterSpacing: '0.18em',
          color: 'var(--accent)',
          textTransform: 'uppercase',
          marginBottom: 16,
        }}
      >
        {title}
      </div>
      {children}
    </div>
  );
}

function Field({ label, value }: { label: string; value: React.ReactNode }) {
  return (
    <div>
      <div
        style={{
          fontSize: 10,
          fontWeight: 'var(--weight-bold)',
          letterSpacing: '0.14em',
          color: 'var(--text-muted)',
          textTransform: 'uppercase',
          marginBottom: 6,
        }}
      >
        {label}
      </div>
      <div
        style={{
          fontSize: 'var(--text-sm)',
          fontWeight: 'var(--weight-semibold)',
          color: 'var(--text-strong)',
        }}
      >
        {value}
      </div>
    </div>
  );
}

function DetailsTab({ title, klass }: { title: Title; klass: FidcClass }) {
  return (
    <div className="flex flex-col" style={{ gap: 32 }}>
      <Section title="Informações do Título">
        <div className="grid" style={{ gridTemplateColumns: 'repeat(4, 1fr)', gap: 24 }}>
          <Field label="Classe de Origem" value={klass.name} />
          <Field label="ID de Lastro" value={`LST-${title.numero}`} />
          <Field label="Número" value={<span className="flex items-center" style={{ gap: 6 }}>#{title.numero}<CopyButton value={title.numero} /></span>} />
          <Field label="Tipo de Ativo" value={title.lastro.replace('_', '-')} />
        </div>
      </Section>

      <Section title="Datas e Prazos">
        <div className="grid" style={{ gridTemplateColumns: 'repeat(4, 1fr)', gap: 24 }}>
          <Field label="Data de Emissão" value={title.emissao} />
          <Field label="Data de Vencimento" value={title.vencimento} />
          <Field label="Prorrogação" value="Não aplicável" />
          <Field label="Protesto" value="—" />
        </div>
      </Section>

      <Section title="Participantes">
        <div className="grid" style={{ gridTemplateColumns: '1fr 1fr', gap: 16 }}>
          <Participant role="Cedente" name={title.cedente} cnpj={title.cedenteCnpj} icon={Building2} />
          <Participant role="Sacado"  name={title.sacado}  cnpj={title.sacadoCnpj}  icon={User} />
        </div>
      </Section>

      <Section title="Contato Regulatório">
        <div className="grid" style={{ gridTemplateColumns: 'repeat(2, 1fr)', gap: 24 }}>
          <Field
            label="Email"
            value={
              <span className="flex items-center" style={{ gap: 6 }}>
                <Mail size={14} color="var(--text-muted)" /> cobranca@cedente.com.br
                <CopyButton value="cobranca@cedente.com.br" />
              </span>
            }
          />
          <Field
            label="Telefone"
            value={
              <span className="flex items-center" style={{ gap: 6 }}>
                <Phone size={14} color="var(--text-muted)" /> +55 (11) 4002-8922
                <CopyButton value="+55 (11) 4002-8922" />
              </span>
            }
          />
        </div>
      </Section>
    </div>
  );
}

function Participant({
  role,
  name,
  cnpj,
  icon: Icon,
}: {
  role: string;
  name: string;
  cnpj: string;
  icon: typeof Building2;
}) {
  return (
    <div
      className="flex items-center"
      style={{
        gap: 14,
        padding: 16,
        background: 'var(--surface-sunken)',
        borderRadius: 'var(--radius-lg)',
      }}
    >
      <div
        className="flex items-center justify-center"
        style={{
          width: 44,
          height: 44,
          borderRadius: 'var(--radius-lg)',
          background: 'var(--surface-card)',
          color: 'var(--gci-base)',
          flexShrink: 0,
        }}
      >
        <Icon size={20} />
      </div>
      <div style={{ flex: 1, minWidth: 0 }}>
        <div
          style={{
            fontSize: 10,
            fontWeight: 'var(--weight-bold)',
            letterSpacing: '0.14em',
            color: 'var(--text-muted)',
            textTransform: 'uppercase',
            marginBottom: 4,
          }}
        >
          {role}
        </div>
        <div
          style={{
            fontSize: 'var(--text-sm)',
            fontWeight: 'var(--weight-bold)',
            color: 'var(--text-strong)',
          }}
        >
          {name}
        </div>
        <div className="flex items-center" style={{ fontSize: 'var(--text-xs)', color: 'var(--text-muted)', marginTop: 2, gap: 4 }}>
          {cnpj}<CopyButton value={cnpj} />
        </div>
      </div>
    </div>
  );
}

function AnexosTab({ title }: { title: Title }) {
  const files = [
    { name: `NFE-${title.numero}.xml`, size: '14 KB', type: 'XML' },
    { name: `DANFE-${title.numero}.pdf`, size: '128 KB', type: 'PDF' },
    { name: `Canhoto-${title.numero}.jpg`, size: '342 KB', type: 'IMG' },
  ];
  return (
    <Section title="Evidências e Lastro Físico">
      <div className="flex flex-col" style={{ gap: 12 }}>
        {files.map((f) => (
          <div
            key={f.name}
            className="flex items-center"
            style={{
              gap: 14,
              padding: 14,
              background: 'var(--surface-sunken)',
              borderRadius: 'var(--radius-lg)',
            }}
          >
            <div
              className="flex items-center justify-center"
              style={{
                width: 40,
                height: 40,
                borderRadius: 'var(--radius-md)',
                background: 'var(--gci-light)',
                color: 'var(--gci-base)',
                fontSize: 10,
                fontWeight: 'var(--weight-bold)',
                letterSpacing: '0.08em',
              }}
            >
              {f.type}
            </div>
            <div style={{ flex: 1 }}>
              <div
                style={{
                  fontSize: 'var(--text-sm)',
                  fontWeight: 'var(--weight-bold)',
                  color: 'var(--text-strong)',
                }}
              >
                {f.name}
              </div>
              <div style={{ fontSize: 'var(--text-xs)', color: 'var(--text-muted)', marginTop: 2 }}>
                {f.size}
              </div>
            </div>
            <button
              className="flex items-center"
              style={{
                gap: 8,
                padding: '8px 14px',
                background: 'var(--surface-card)',
                color: 'var(--text-strong)',
                borderWidth: 1,
                borderStyle: 'solid',
                borderColor: 'var(--border-default)',
                borderRadius: 'var(--radius-md)',
                cursor: 'pointer',
                fontSize: 'var(--text-xs)',
                fontWeight: 'var(--weight-bold)',
              }}
            >
              <Download size={14} /> Baixar
            </button>
          </div>
        ))}
      </div>
    </Section>
  );
}

function MovimentoTab({ title }: { title: Title }) {
  const events = [
    { date: title.emissao, label: 'Título emitido pelo cedente', tone: 'info' },
    { date: title.emissao, label: 'Registro enviado à registradora (CERC)', tone: 'info' },
    {
      date: title.emissao,
      label: 'Confirmação física do sacado',
      tone: title.status === 'CONFIRMADO' ? 'success' : 'warning',
    },
    {
      date: title.vencimento,
      label:
        title.status === 'VENCIDO'
          ? 'Inadimplência identificada'
          : 'Vencimento programado',
      tone: title.status === 'VENCIDO' ? 'danger' : 'neutral',
    },
  ];
  const toneMap: Record<string, string> = {
    info: 'var(--gci-base)',
    success: 'var(--success-base)',
    warning: 'var(--warning-base)',
    danger: 'var(--danger-base)',
    neutral: 'var(--neutral-300)',
  };
  return (
    <Section title="Linha do Tempo">
      <div className="flex flex-col" style={{ gap: 0, position: 'relative' }}>
        {events.map((e, i) => (
          <div
            key={i}
            className="flex items-start"
            style={{ gap: 16, padding: '12px 0', position: 'relative' }}
          >
            <div style={{ position: 'relative', width: 12 }}>
              <span
                style={{
                  display: 'block',
                  width: 12,
                  height: 12,
                  borderRadius: '9999px',
                  background: toneMap[e.tone],
                  marginTop: 6,
                }}
              />
              {i < events.length - 1 && (
                <span
                  style={{
                    position: 'absolute',
                    left: 5,
                    top: 18,
                    bottom: -12,
                    width: 2,
                    background: 'var(--border-default)',
                  }}
                />
              )}
            </div>
            <div style={{ flex: 1 }}>
              <div
                style={{
                  fontSize: 'var(--text-sm)',
                  fontWeight: 'var(--weight-semibold)',
                  color: 'var(--text-strong)',
                }}
              >
                {e.label}
              </div>
              <div style={{ fontSize: 'var(--text-xs)', color: 'var(--text-muted)', marginTop: 2 }}>
                {e.date}
              </div>
            </div>
          </div>
        ))}
      </div>
    </Section>
  );
}

function AccrualTab({ title }: { title: Title }) {
  const rows = [
    { data: title.emissao,   taxa: '1,8500%', base: '252', accrual: brl(title.vrNominal * 0.0185 / 252), acumulado: brl(title.vrNominal * 0.0185 / 252 * 3) },
    { data: title.emissao,   taxa: '1,8500%', base: '252', accrual: brl(title.vrNominal * 0.0185 / 252), acumulado: brl(title.vrNominal * 0.0185 / 252 * 2) },
    { data: title.vencimento, taxa: '1,8500%', base: '252', accrual: brl(title.vrNominal * 0.0185 / 252), acumulado: brl(title.vrNominal * 0.0185 / 252) },
  ];
  return (
    <Section title="Cálculo de Accrual">
      <div style={{ borderWidth: 1, borderStyle: 'solid', borderColor: 'var(--border-default)', borderRadius: 'var(--radius-lg)', overflow: 'hidden' }}>
        <div className="grid" style={{ gridTemplateColumns: '1fr 1fr 1fr 1fr 1fr', padding: '12px 16px', background: 'var(--surface-sunken)', fontSize: 10, fontWeight: 'var(--weight-bold)', letterSpacing: '0.14em', color: 'var(--text-muted)', textTransform: 'uppercase' }}>
          <div>Data</div><div>Taxa</div><div>Base</div><div>Accrual Diário</div><div style={{ textAlign: 'right' }}>Acumulado</div>
        </div>
        {rows.map((r, i) => (
          <div key={i} className="grid items-center" style={{ gridTemplateColumns: '1fr 1fr 1fr 1fr 1fr', padding: '14px 16px', borderTop: '1px solid var(--border-default)', fontSize: 'var(--text-sm)', fontVariantNumeric: 'tabular-nums' }}>
            <div style={{ color: 'var(--text-muted)' }}>{r.data}</div>
            <div style={{ fontWeight: 'var(--weight-semibold)', color: 'var(--text-strong)' }}>{r.taxa}</div>
            <div style={{ color: 'var(--text-muted)' }}>{r.base}</div>
            <div style={{ fontWeight: 'var(--weight-semibold)', color: 'var(--text-strong)' }}>{r.accrual}</div>
            <div style={{ fontWeight: 'var(--weight-bold)', color: 'var(--text-strong)', textAlign: 'right' }}>{r.acumulado}</div>
          </div>
        ))}
      </div>
    </Section>
  );
}

function ConfirmacoesTab({ title }: { title: Title }) {
  const confirmacoes = [
    { data: title.emissao, tipo: 'Confirmação do Sacado', resultado: title.status === 'CONFIRMADO' ? 'CONFIRMADO' : 'PENDENTE', obs: 'Via portal eletrônico' },
    { data: title.emissao, tipo: 'Validação de Lastro', resultado: 'CONFIRMADO', obs: 'Documento verificado' },
    { data: title.emissao, tipo: 'Registro Registradora', resultado: 'CONFIRMADO', obs: 'B3 — protocolo #82341' },
  ];
  const toneMap: Record<string, { bg: string; fg: string }> = {
    CONFIRMADO: { bg: 'var(--success-light)', fg: 'var(--success-dark)' },
    PENDENTE:   { bg: 'var(--warning-light)', fg: 'var(--warning-base)' },
    REJEITADO:  { bg: 'var(--danger-light)',  fg: 'var(--danger-base)' },
  };
  return (
    <Section title="Histórico de Confirmações">
      <div className="flex flex-col" style={{ gap: 10 }}>
        {confirmacoes.map((c, i) => (
          <div key={i} className="flex items-center" style={{ gap: 14, padding: 14, background: 'var(--surface-sunken)', borderRadius: 'var(--radius-lg)' }}>
            <div style={{ flex: 1 }}>
              <div style={{ fontSize: 'var(--text-sm)', fontWeight: 'var(--weight-bold)', color: 'var(--text-strong)' }}>{c.tipo}</div>
              <div style={{ fontSize: 'var(--text-xs)', color: 'var(--text-muted)', marginTop: 2 }}>{c.data} · {c.obs}</div>
            </div>
            <span style={{ fontSize: 10, fontWeight: 'var(--weight-bold)', letterSpacing: '0.10em', padding: '5px 10px', borderRadius: '9999px', background: (toneMap[c.resultado] ?? toneMap['PENDENTE']).bg, color: (toneMap[c.resultado] ?? toneMap['PENDENTE']).fg }}>
              {c.resultado}
            </span>
          </div>
        ))}
      </div>
    </Section>
  );
}

type MovSub = 'registro' | 'cessao';

function MovimentacoesTab({ title }: { title: Title }) {
  const [sub, setSub] = useState<MovSub>('registro');
  const registros = [
    { data: title.emissao,    operacao: 'Inclusão',  registradora: 'B3',  protocolo: '#82341', valor: brl(title.vrNominal) },
    { data: title.vencimento, operacao: 'Atualização', registradora: 'B3', protocolo: '#82411', valor: brl(title.vrNominal * 0.98) },
  ];
  const cessoes = [
    { data: title.emissao, cedente: title.cedente, cessionario: 'FIDC Fundo', valor: brl(title.vrNominal), status: 'LIQUIDADO' },
  ];
  return (
    <div className="flex flex-col" style={{ gap: 20 }}>
      {/* Sub-navigation */}
      <div className="flex" style={{ gap: 4, padding: 4, background: 'var(--surface-sunken)', borderRadius: 'var(--radius-lg)', alignSelf: 'flex-start' }}>
        {(['registro', 'cessao'] as MovSub[]).map((s) => (
          <button key={s} onClick={() => setSub(s)} style={{
            padding: '8px 16px', fontSize: 'var(--text-xs)', fontWeight: 'var(--weight-bold)',
            letterSpacing: '0.10em', border: 'none', cursor: 'pointer', borderRadius: 'var(--radius-md)',
            background: sub === s ? 'var(--surface-card)' : 'transparent',
            color: sub === s ? 'var(--text-strong)' : 'var(--text-muted)',
            boxShadow: sub === s ? 'var(--shadow-xs)' : 'none',
            transition: 'all var(--duration-base)',
          }}>
            {s === 'registro' ? 'MOVIMENTAÇÕES DE REGISTRO' : 'MOVIMENTO DE CESSÃO'}
          </button>
        ))}
      </div>

      {sub === 'registro' && (
        <Section title="Movimentações de Registro">
          <div style={{ borderWidth: 1, borderStyle: 'solid', borderColor: 'var(--border-default)', borderRadius: 'var(--radius-lg)', overflow: 'hidden' }}>
            <div className="grid" style={{ gridTemplateColumns: '1fr 1fr 1fr 1fr 1fr', padding: '12px 16px', background: 'var(--surface-sunken)', fontSize: 10, fontWeight: 'var(--weight-bold)', letterSpacing: '0.14em', color: 'var(--text-muted)', textTransform: 'uppercase' }}>
              <div>Data</div><div>Operação</div><div>Registradora</div><div>Protocolo</div><div style={{ textAlign: 'right' }}>Valor</div>
            </div>
            {registros.map((r, i) => (
              <div key={i} className="grid items-center" style={{ gridTemplateColumns: '1fr 1fr 1fr 1fr 1fr', padding: '14px 16px', borderTop: '1px solid var(--border-default)', fontSize: 'var(--text-sm)' }}>
                <div style={{ color: 'var(--text-muted)' }}>{r.data}</div>
                <div style={{ fontWeight: 'var(--weight-semibold)', color: 'var(--text-strong)' }}>{r.operacao}</div>
                <div style={{ color: 'var(--text-default)' }}>{r.registradora}</div>
                <div style={{ color: 'var(--text-muted)', fontSize: 'var(--text-xs)' }}>{r.protocolo}</div>
                <div style={{ fontWeight: 'var(--weight-bold)', color: 'var(--text-strong)', textAlign: 'right', fontVariantNumeric: 'tabular-nums' }}>{r.valor}</div>
              </div>
            ))}
          </div>
        </Section>
      )}

      {sub === 'cessao' && (
        <Section title="Movimento de Cessão">
          <div style={{ borderWidth: 1, borderStyle: 'solid', borderColor: 'var(--border-default)', borderRadius: 'var(--radius-lg)', overflow: 'hidden' }}>
            <div className="grid" style={{ gridTemplateColumns: '1fr 1.4fr 1.4fr 1fr 1fr', padding: '12px 16px', background: 'var(--surface-sunken)', fontSize: 10, fontWeight: 'var(--weight-bold)', letterSpacing: '0.14em', color: 'var(--text-muted)', textTransform: 'uppercase' }}>
              <div>Data</div><div>Cedente</div><div>Cessionário</div><div>Valor</div><div style={{ textAlign: 'right' }}>Status</div>
            </div>
            {cessoes.map((r, i) => (
              <div key={i} className="grid items-center" style={{ gridTemplateColumns: '1fr 1.4fr 1.4fr 1fr 1fr', padding: '14px 16px', borderTop: '1px solid var(--border-default)', fontSize: 'var(--text-sm)' }}>
                <div style={{ color: 'var(--text-muted)' }}>{r.data}</div>
                <div style={{ fontWeight: 'var(--weight-semibold)', color: 'var(--text-strong)' }}>{r.cedente}</div>
                <div style={{ fontWeight: 'var(--weight-semibold)', color: 'var(--text-strong)' }}>{r.cessionario}</div>
                <div style={{ fontWeight: 'var(--weight-bold)', color: 'var(--text-strong)', fontVariantNumeric: 'tabular-nums' }}>{r.valor}</div>
                <div style={{ textAlign: 'right' }}>
                  <span style={{ fontSize: 9, fontWeight: 'var(--weight-bold)', letterSpacing: '0.10em', padding: '4px 8px', borderRadius: '9999px', background: 'var(--success-light)', color: 'var(--success-dark)' }}>{r.status}</span>
                </div>
              </div>
            ))}
          </div>
        </Section>
      )}
    </div>
  );
}

// src/features/fidc/screens/TitleDetailScreen.vue
<script setup lang="ts">
import { ref, computed } from 'vue';
import {
  ArrowLeft,
  FileText,
  Paperclip,
  CreditCard,
  Activity,
  CheckCircle2,
  Clock,
  TrendingUp,
  BadgeCheck,
  ArrowLeftRight,
} from 'lucide-vue-next';
import { brl, detalhePagamentos, type Fidc, type FidcClass, type Title, type TitleStatus } from '../data/fidcsData';
import PagamentosTab from './detail-tabs/PagamentosTab.vue';
import CopyButton from './title-detail/CopyButton.vue';
import TabPill from './title-detail/TabPill.vue';
import DetailsTab from './title-detail/DetailsTab.vue';
import AnexosTab from './title-detail/AnexosTab.vue';
import AccrualTab from './title-detail/AccrualTab.vue';
import ConfirmacoesTab from './title-detail/ConfirmacoesTab.vue';
import MovimentacoesTab from './title-detail/MovimentacoesTab.vue';
import MovimentoTab from './title-detail/MovimentoTab.vue';

const props = defineProps<{ fidc: Fidc; klass: FidcClass; title: Title }>();
const emit = defineEmits<{ back: [] }>();

type Tab = 'detalhes' | 'anexos' | 'accrual' | 'pagamentos' | 'confirmacoes' | 'movimentacoes' | 'historico';

const statusTone: Record<TitleStatus, { bg: string; fg: string; iconBg: string }> = {
  CONFIRMADO: { bg: 'var(--success-light)', fg: 'var(--success-dark)', iconBg: 'var(--success-base)' },
  PENDENTE: { bg: 'var(--warning-light)', fg: 'var(--warning-dark)', iconBg: 'var(--warning-base)' },
  VENCIDO: { bg: 'var(--danger-light)', fg: 'var(--danger-dark)', iconBg: 'var(--danger-base)' },
};

const tab = ref<Tab>('detalhes');
const det = ref(detalhePagamentos(props.title));
const tone = computed(() => statusTone[props.title.status]);
</script>

<template>
  <div class="flex flex-col" style="gap: 24px">
    <!-- Header -->
    <div class="flex items-center" style="gap: 16px">
      <button
        aria-label="Voltar"
        class="flex items-center justify-center"
        style="
          width: 48px;
          height: 48px;
          border-radius: var(--radius-lg);
          background: var(--surface-card);
          border-width: 1px;
          border-style: solid;
          border-color: var(--border-default);
          cursor: pointer;
          color: var(--text-strong);
        "
        @click="emit('back')"
      >
        <ArrowLeft :size="20" />
      </button>
      <div style="flex: 1">
        <div style="font-size: 10px; font-weight: var(--weight-bold); letter-spacing: 0.18em; color: var(--agro-base); text-transform: uppercase; margin-bottom: 4px">
          {{ fidc.name }} • {{ klass.name }}
        </div>
        <h2 class="flex items-center" style="font-size: var(--text-xl); font-weight: var(--weight-bold); color: var(--text-strong); letter-spacing: -0.01em; line-height: 1.2; gap: 8px">
          Título #{{ title.numero }}
          <CopyButton :value="`Título #${title.numero}`" />
        </h2>
        <p style="font-size: var(--text-sm); color: var(--text-muted); margin-top: 4px">
          Auditoria e ciclo de vida do direito creditório
        </p>
      </div>
      <span
        class="flex items-center"
        :style="{
          gap: '8px',
          fontSize: '11px',
          fontWeight: 'var(--weight-bold)',
          letterSpacing: '0.12em',
          padding: '8px 14px',
          background: tone.bg,
          color: tone.fg,
          borderRadius: '9999px',
        }"
      >
        <CheckCircle2 v-if="title.status === 'CONFIRMADO'" :size="14" />
        <Clock v-else :size="14" />
        {{ title.status }}
      </span>
    </div>

    <!-- Painel valor -->
    <div
      class="relative overflow-hidden flex items-center"
      style="
        background: var(--gci-base);
        border-radius: var(--radius-xl);
        padding: 28px 32px;
        color: #fff;
        box-shadow: 0 20px 40px -20px rgba(8,60,74,0.40);
      "
    >
      <div style="position: absolute; top: -100px; right: -100px; width: 320px; height: 320px; border-radius: 9999px; background: rgba(255,255,255,0.04)" />
      <div style="flex: 1; position: relative; z-index: 1">
        <div style="font-size: 11px; font-weight: var(--weight-bold); letter-spacing: 0.18em; color: var(--agro-base); text-transform: uppercase; margin-bottom: 10px">
          Valor Nominal do Título
        </div>
        <div style="font-size: 36px; font-weight: var(--weight-bold); letter-spacing: -0.02em; font-variant-numeric: tabular-nums; line-height: 1.1">
          {{ brl(title.vrNominal) }}
        </div>
        <div style="font-size: var(--text-xs); color: rgba(255,255,255,0.65); margin-top: 8px">
          Lastro: {{ title.lastro.replace('_', '-') }} • Emissão {{ title.emissao }} • Vencimento
          {{ title.vencimento }}
        </div>
      </div>
    </div>

    <!-- Tabs -->
    <div
      class="flex items-center"
      style="gap: 4px; padding: 4px; background: var(--surface-card); border-width: 1px; border-style: solid; border-color: var(--border-default); border-radius: var(--radius-xl); align-self: flex-start"
    >
      <TabPill :active="tab === 'detalhes'" :icon="FileText" @click="tab = 'detalhes'">Detalhes</TabPill>
      <TabPill :active="tab === 'anexos'" :icon="Paperclip" @click="tab = 'anexos'">Anexos</TabPill>
      <TabPill :active="tab === 'accrual'" :icon="TrendingUp" @click="tab = 'accrual'">Accrual</TabPill>
      <TabPill :active="tab === 'pagamentos'" :icon="CreditCard" @click="tab = 'pagamentos'">Pagamentos</TabPill>
      <TabPill :active="tab === 'confirmacoes'" :icon="BadgeCheck" @click="tab = 'confirmacoes'">Confirmações</TabPill>
      <TabPill :active="tab === 'movimentacoes'" :icon="ArrowLeftRight" @click="tab = 'movimentacoes'">Movimentações</TabPill>
      <TabPill :active="tab === 'historico'" :icon="Activity" @click="tab = 'historico'">Histórico</TabPill>
    </div>

    <div
      style="
        background: var(--surface-card);
        border-width: 1px;
        border-style: solid;
        border-color: var(--border-default);
        border-radius: var(--radius-xl);
        padding: 24px;
      "
    >
      <DetailsTab v-if="tab === 'detalhes'" :title="title" :klass="klass" />
      <AnexosTab v-else-if="tab === 'anexos'" :title="title" />
      <AccrualTab v-else-if="tab === 'accrual'" :title="title" />
      <PagamentosTab v-else-if="tab === 'pagamentos'" :title="title" v-model:det="det" />
      <ConfirmacoesTab v-else-if="tab === 'confirmacoes'" :title="title" />
      <MovimentacoesTab v-else-if="tab === 'movimentacoes'" :title="title" />
      <MovimentoTab v-else-if="tab === 'historico'" :title="title" />
    </div>
  </div>
</template>
