// src/features/risco/screens/detail-tabs/ParametrizacoesTab.tsx
import { useState } from 'react';
import type { Parametrizacoes } from '../../data/riscoData';
import { LimiteSubTab } from './LimiteSubTab';
import { AutoatendimentoSubTab } from './AutoatendimentoSubTab';
import { GeralSubTab } from './GeralSubTab';
import { GarantiaSubTab } from './GarantiaSubTab';

interface Props {
  data: Parametrizacoes;
  onChange: (data: Parametrizacoes) => void;
}

const SUB_TABS = ['Limite', 'Autoatendimento', 'Geral', 'Garantia'] as const;
type SubTab = typeof SUB_TABS[number];

export function ParametrizacoesTab({ data, onChange }: Props) {
  const [tab, setTab] = useState<SubTab>('Limite');

  return (
    <div className="flex flex-col" style={{ gap: 20 }}>
      <div className="flex items-center" style={{ gap: 6, borderBottom: '1px solid var(--border-default)' }}>
        {SUB_TABS.map((t) => (
          <button
            key={t}
            onClick={() => setTab(t)}
            style={{
              padding: '10px 4px', marginRight: 22, background: 'none', border: 'none', cursor: 'pointer',
              fontSize: 'var(--text-sm)', fontWeight: 'var(--weight-bold)',
              color: tab === t ? 'var(--text-strong)' : 'var(--text-muted)',
              borderBottom: tab === t ? '2px solid var(--accent)' : '2px solid transparent',
              marginBottom: -1,
            }}
          >
            {t}
          </button>
        ))}
      </div>

      {tab === 'Limite' && <LimiteSubTab data={data.limite} onSave={(limite) => onChange({ ...data, limite })} />}
      {tab === 'Autoatendimento' && <AutoatendimentoSubTab data={data.autoatendimento} onSave={(autoatendimento) => onChange({ ...data, autoatendimento })} />}
      {tab === 'Geral' && <GeralSubTab data={data.geral} onSave={(geral) => onChange({ ...data, geral })} />}
      {tab === 'Garantia' && <GarantiaSubTab data={data.garantia} onSave={(garantia) => onChange({ ...data, garantia })} />}
    </div>
  );
}

// src/features/risco/screens/detail-tabs/ParametrizacoesTab.vue
<script setup lang="ts">
import { ref } from 'vue';
import type { Parametrizacoes } from '../../data/riscoData';
import LimiteSubTab from './LimiteSubTab.vue';
import AutoatendimentoSubTab from './AutoatendimentoSubTab.vue';
import GeralSubTab from './GeralSubTab.vue';
import GarantiaSubTab from './GarantiaSubTab.vue';

interface Props {
  data: Parametrizacoes;
}

defineProps<Props>();
const emit = defineEmits<{ change: [data: Parametrizacoes] }>();

const SUB_TABS = ['Limite', 'Autoatendimento', 'Geral', 'Garantia'] as const;
type SubTab = (typeof SUB_TABS)[number];

const tab = ref<SubTab>('Limite');
</script>

<template>
  <div class="flex flex-col" style="gap: 20px">
    <div class="flex items-center" style="gap: 6px; border-bottom: 1px solid var(--border-default)">
      <button
        v-for="t in SUB_TABS"
        :key="t"
        :style="{
          padding: '10px 4px', marginRight: '22px', background: 'none', border: 'none', cursor: 'pointer',
          fontSize: 'var(--text-sm)', fontWeight: 'var(--weight-bold)',
          color: tab === t ? 'var(--text-strong)' : 'var(--text-muted)',
          borderBottom: tab === t ? '2px solid var(--accent)' : '2px solid transparent',
          marginBottom: '-1px',
        }"
        @click="tab = t"
      >
        {{ t }}
      </button>
    </div>

    <LimiteSubTab v-if="tab === 'Limite'" :data="data.limite" @save="(limite) => emit('change', { ...data, limite })" />
    <AutoatendimentoSubTab v-if="tab === 'Autoatendimento'" :data="data.autoatendimento" @save="(autoatendimento) => emit('change', { ...data, autoatendimento })" />
    <GeralSubTab v-if="tab === 'Geral'" :data="data.geral" @save="(geral) => emit('change', { ...data, geral })" />
    <GarantiaSubTab v-if="tab === 'Garantia'" :data="data.garantia" @save="(garantia) => emit('change', { ...data, garantia })" />
  </div>
</template>
