// src/features/risco/components/modals/EditarCadastroCedenteModal.vue
<script setup lang="ts">
import { ref } from 'vue';
import { X } from 'lucide-vue-next';
import { NACIONALIDADE_OPTS, ESTADO_CIVIL_OPTS, type Cedente } from '../../data/riscoData';
import { FieldLabel, FormField, SelectField } from '../../screens/detail-tabs/shared';

const props = defineProps<{ cedente: Cedente }>();
const emit = defineEmits<{ close: []; update: [cedente: Cedente] }>();

const isPF = props.cedente.tipo === 'Pessoa Física';

const rg = ref(props.cedente.rg ?? '');
const inscricaoProdutorRural = ref(props.cedente.inscricaoProdutorRural ?? '');
const nacionalidade = ref(props.cedente.nacionalidade ?? '');
const profissao = ref(props.cedente.profissao ?? '');
const estadoCivil = ref(props.cedente.estadoCivil ?? '');

const nomeFantasia = ref(props.cedente.nomeFantasia ?? '');
const tipoEmpresa = ref(props.cedente.tipoEmpresa ?? '');
const porte = ref(props.cedente.porte ?? '');
const atividadePrincipal = ref(props.cedente.atividadePrincipal ?? '');
const naturezaJuridica = ref(props.cedente.naturezaJuridica ?? '');
const inscricaoMunicipal = ref(props.cedente.inscricaoMunicipal ?? '');
const inscricaoEstadual = ref(props.cedente.inscricaoEstadual ?? '');

function handleAtualizar() {
  if (isPF) {
    emit('update', { ...props.cedente, rg: rg.value, inscricaoProdutorRural: inscricaoProdutorRural.value, nacionalidade: nacionalidade.value, profissao: profissao.value, estadoCivil: estadoCivil.value });
  } else {
    emit('update', {
      ...props.cedente, nomeFantasia: nomeFantasia.value, tipoEmpresa: tipoEmpresa.value, porte: porte.value,
      atividadePrincipal: atividadePrincipal.value, naturezaJuridica: naturezaJuridica.value,
      inscricaoMunicipal: inscricaoMunicipal.value, inscricaoEstadual: inscricaoEstadual.value,
    });
  }
}
</script>

<template>
  <div
    style="
      position: fixed; inset: 0;
      background: rgba(8,60,74,0.55); backdrop-filter: blur(8px);
      z-index: 450; display: flex; align-items: center; justify-content: center;
      padding: 32px; animation: fadeIn 0.2s ease-out;
    "
  >
    <div
      class="flex flex-col"
      style="
        background: var(--surface-card); border-radius: var(--radius-xl);
        width: 100%; max-width: 760px; max-height: 90vh;
        overflow: hidden; box-shadow: var(--shadow-lg);
      "
      @click.stop
    >
      <!-- Header -->
      <div class="flex items-center justify-between" style="padding: 20px 28px; border-bottom: 1px solid var(--border-default); flex-shrink: 0">
        <h2 style="font-size: var(--text-lg); font-weight: var(--weight-bold); color: var(--text-strong)">
          Editar Cadastro
        </h2>
        <button
          aria-label="Fechar"
          class="flex items-center justify-center"
          style="width: 32px; height: 32px; border-radius: var(--radius-lg); border: 1px solid var(--border-default); background: var(--surface-card); cursor: pointer; color: var(--text-muted)"
          @click="emit('close')"
        >
          <X :size="16" />
        </button>
      </div>

      <!-- Body -->
      <div style="padding: 24px; overflow: auto">
        <div v-if="isPF" class="grid" style="grid-template-columns: repeat(12, 1fr); gap: 16px">
          <div style="grid-column: span 4">
            <FieldLabel>CPF</FieldLabel>
            <div style="height: 40px; display: flex; align-items: center; padding: 0 14px; background: var(--surface-sunken); border: 1px solid var(--border-default); border-radius: var(--radius-lg); color: var(--text-disabled); font-size: var(--text-sm); cursor: not-allowed; font-variant-numeric: tabular-nums">
              {{ cedente.documento || '—' }}
            </div>
          </div>
          <div style="grid-column: span 5">
            <FieldLabel>Nome</FieldLabel>
            <div style="height: 40px; display: flex; align-items: center; padding: 0 14px; background: var(--surface-sunken); border: 1px solid var(--border-default); border-radius: var(--radius-lg); color: var(--text-disabled); font-size: var(--text-sm); cursor: not-allowed; font-variant-numeric: tabular-nums">
              {{ cedente.nome || '—' }}
            </div>
          </div>
          <div style="grid-column: span 3">
            <FormField label="RG" placeholder="—" v-model="rg" />
          </div>

          <div style="grid-column: span 4">
            <FormField label="Inscrição do produtor rural" placeholder="—" v-model="inscricaoProdutorRural" />
          </div>
          <div style="grid-column: span 4">
            <SelectField label="Nacionalidade" :options="NACIONALIDADE_OPTS" placeholder="Selecione" :value="nacionalidade" @change="nacionalidade = ($event.target as HTMLSelectElement).value" />
          </div>
          <div style="grid-column: span 4">
            <FieldLabel>Data de nascimento</FieldLabel>
            <div style="height: 40px; display: flex; align-items: center; padding: 0 14px; background: var(--surface-sunken); border: 1px solid var(--border-default); border-radius: var(--radius-lg); color: var(--text-disabled); font-size: var(--text-sm); cursor: not-allowed; font-variant-numeric: tabular-nums">
              {{ cedente.dataNascimento || '—' }}
            </div>
          </div>

          <div style="grid-column: span 6">
            <FormField label="Profissão" placeholder="—" v-model="profissao" />
          </div>
          <div style="grid-column: span 6">
            <SelectField label="Estado Civil" :options="ESTADO_CIVIL_OPTS" placeholder="Selecione" :value="estadoCivil" @change="estadoCivil = ($event.target as HTMLSelectElement).value" />
          </div>
        </div>
        <div v-else class="grid" style="grid-template-columns: repeat(12, 1fr); gap: 16px">
          <div style="grid-column: span 4">
            <FieldLabel>CNPJ</FieldLabel>
            <div style="height: 40px; display: flex; align-items: center; padding: 0 14px; background: var(--surface-sunken); border: 1px solid var(--border-default); border-radius: var(--radius-lg); color: var(--text-disabled); font-size: var(--text-sm); cursor: not-allowed; font-variant-numeric: tabular-nums">
              {{ cedente.documento || '—' }}
            </div>
          </div>
          <div style="grid-column: span 5">
            <FieldLabel>Razão Social</FieldLabel>
            <div style="height: 40px; display: flex; align-items: center; padding: 0 14px; background: var(--surface-sunken); border: 1px solid var(--border-default); border-radius: var(--radius-lg); color: var(--text-disabled); font-size: var(--text-sm); cursor: not-allowed; font-variant-numeric: tabular-nums">
              {{ cedente.razaoSocial ?? cedente.nome ?? '—' }}
            </div>
          </div>
          <div style="grid-column: span 3">
            <FormField label="Nome Fantasia" placeholder="—" v-model="nomeFantasia" />
          </div>

          <div style="grid-column: span 4">
            <FieldLabel>Data de abertura</FieldLabel>
            <div style="height: 40px; display: flex; align-items: center; padding: 0 14px; background: var(--surface-sunken); border: 1px solid var(--border-default); border-radius: var(--radius-lg); color: var(--text-disabled); font-size: var(--text-sm); cursor: not-allowed; font-variant-numeric: tabular-nums">
              {{ cedente.dataAbertura || '—' }}
            </div>
          </div>
          <div style="grid-column: span 4">
            <FormField label="Tipo" placeholder="—" v-model="tipoEmpresa" />
          </div>
          <div style="grid-column: span 4">
            <FormField label="Porte" placeholder="—" v-model="porte" />
          </div>

          <div style="grid-column: span 6">
            <FormField label="Atividade principal" placeholder="—" v-model="atividadePrincipal" />
          </div>
          <div style="grid-column: span 6">
            <FormField label="Natureza Jurídica" placeholder="—" v-model="naturezaJuridica" />
          </div>

          <div style="grid-column: span 6">
            <FormField label="Inscrição municipal" placeholder="—" v-model="inscricaoMunicipal" />
          </div>
          <div style="grid-column: span 6">
            <FormField label="Inscrição estadual" placeholder="—" v-model="inscricaoEstadual" />
          </div>
        </div>
      </div>

      <!-- Footer -->
      <div class="flex items-center justify-end" style="gap: 12px; padding: 16px 28px; border-top: 1px solid var(--border-default); flex-shrink: 0">
        <button
          style="height: 40px; padding: 0 20px; background: none; border: none; cursor: pointer; color: var(--text-muted); font-weight: var(--weight-semibold); font-size: var(--text-sm)"
          @click="emit('close')"
        >
          Cancelar
        </button>
        <button
          style="height: 40px; padding: 0 24px; border: none; border-radius: var(--radius-lg); cursor: pointer; font-weight: var(--weight-bold); font-size: var(--text-xs); letter-spacing: 0.08em; background: var(--action-primary-bg); color: #fff"
          @click="handleAtualizar"
        >
          ATUALIZAR
        </button>
      </div>
    </div>
  </div>
</template>

// src/features/risco/components/modals/EditarCadastroCedenteModal.tsx
import { useState } from 'react';
import { X } from 'lucide-react';
import { NACIONALIDADE_OPTS, ESTADO_CIVIL_OPTS, type Cedente } from '../../data/riscoData';
import { FieldLabel, FormField, SelectField } from '../../screens/detail-tabs/shared';

interface Props {
  cedente: Cedente;
  onClose: () => void;
  onUpdate: (cedente: Cedente) => void;
}

function Cell({ span, children }: { span: number; children: React.ReactNode }) {
  return <div style={{ gridColumn: `span ${span}` }}>{children}</div>;
}

function ReadonlyField({ label, value }: { label: string; value?: string }) {
  return (
    <div>
      <FieldLabel>{label}</FieldLabel>
      <div
        style={{
          height: 40, display: 'flex', alignItems: 'center', padding: '0 14px',
          background: 'var(--surface-sunken)', border: '1px solid var(--border-default)',
          borderRadius: 'var(--radius-lg)', color: 'var(--text-disabled)', fontSize: 'var(--text-sm)',
          cursor: 'not-allowed', fontVariantNumeric: 'tabular-nums',
        }}
      >
        {value || '—'}
      </div>
    </div>
  );
}

export function EditarCadastroCedenteModal({ cedente, onClose, onUpdate }: Props) {
  const isPF = cedente.tipo === 'Pessoa Física';

  const [rg, setRg] = useState(cedente.rg ?? '');
  const [inscricaoProdutorRural, setInscricaoProdutorRural] = useState(cedente.inscricaoProdutorRural ?? '');
  const [nacionalidade, setNacionalidade] = useState(cedente.nacionalidade ?? '');
  const [profissao, setProfissao] = useState(cedente.profissao ?? '');
  const [estadoCivil, setEstadoCivil] = useState(cedente.estadoCivil ?? '');

  const [nomeFantasia, setNomeFantasia] = useState(cedente.nomeFantasia ?? '');
  const [tipoEmpresa, setTipoEmpresa] = useState(cedente.tipoEmpresa ?? '');
  const [porte, setPorte] = useState(cedente.porte ?? '');
  const [atividadePrincipal, setAtividadePrincipal] = useState(cedente.atividadePrincipal ?? '');
  const [naturezaJuridica, setNaturezaJuridica] = useState(cedente.naturezaJuridica ?? '');
  const [inscricaoMunicipal, setInscricaoMunicipal] = useState(cedente.inscricaoMunicipal ?? '');
  const [inscricaoEstadual, setInscricaoEstadual] = useState(cedente.inscricaoEstadual ?? '');

  const handleAtualizar = () => {
    if (isPF) {
      onUpdate({ ...cedente, rg, inscricaoProdutorRural, nacionalidade, profissao, estadoCivil });
    } else {
      onUpdate({ ...cedente, nomeFantasia, tipoEmpresa, porte, atividadePrincipal, naturezaJuridica, inscricaoMunicipal, inscricaoEstadual });
    }
  };

  return (
    <div
      style={{
        position: 'fixed', inset: 0,
        background: 'rgba(8,60,74,0.55)', backdropFilter: 'blur(8px)',
        zIndex: 450, display: 'flex', alignItems: 'center', justifyContent: 'center',
        padding: 32, animation: 'fadeIn 0.2s ease-out',
      }}
    >
      <div
        onClick={(e) => e.stopPropagation()}
        className="flex flex-col"
        style={{
          background: 'var(--surface-card)', borderRadius: 'var(--radius-xl)',
          width: '100%', maxWidth: 760, maxHeight: '90vh',
          overflow: 'hidden', boxShadow: 'var(--shadow-lg)',
        }}
      >
        {/* Header */}
        <div className="flex items-center justify-between" style={{ padding: '20px 28px', borderBottom: '1px solid var(--border-default)', flexShrink: 0 }}>
          <h2 style={{ fontSize: 'var(--text-lg)', fontWeight: 'var(--weight-bold)', color: 'var(--text-strong)' }}>
            Editar Cadastro
          </h2>
          <button
            onClick={onClose}
            aria-label="Fechar"
            className="flex items-center justify-center"
            style={{ width: 32, height: 32, borderRadius: 'var(--radius-lg)', border: '1px solid var(--border-default)', background: 'var(--surface-card)', cursor: 'pointer', color: 'var(--text-muted)' }}
          >
            <X size={16} />
          </button>
        </div>

        {/* Body */}
        <div style={{ padding: 24, overflow: 'auto' }}>
          {isPF ? (
            <div className="grid" style={{ gridTemplateColumns: 'repeat(12, 1fr)', gap: 16 }}>
              <Cell span={4}><ReadonlyField label="CPF" value={cedente.documento} /></Cell>
              <Cell span={5}><ReadonlyField label="Nome" value={cedente.nome} /></Cell>
              <Cell span={3}><FormField label="RG" placeholder="—" value={rg} onChange={(e) => setRg(e.target.value)} /></Cell>

              <Cell span={4}><FormField label="Inscrição do produtor rural" placeholder="—" value={inscricaoProdutorRural} onChange={(e) => setInscricaoProdutorRural(e.target.value)} /></Cell>
              <Cell span={4}><SelectField label="Nacionalidade" options={NACIONALIDADE_OPTS} placeholder="Selecione" value={nacionalidade} onChange={(e) => setNacionalidade(e.target.value)} /></Cell>
              <Cell span={4}><ReadonlyField label="Data de nascimento" value={cedente.dataNascimento} /></Cell>

              <Cell span={6}><FormField label="Profissão" placeholder="—" value={profissao} onChange={(e) => setProfissao(e.target.value)} /></Cell>
              <Cell span={6}><SelectField label="Estado Civil" options={ESTADO_CIVIL_OPTS} placeholder="Selecione" value={estadoCivil} onChange={(e) => setEstadoCivil(e.target.value)} /></Cell>
            </div>
          ) : (
            <div className="grid" style={{ gridTemplateColumns: 'repeat(12, 1fr)', gap: 16 }}>
              <Cell span={4}><ReadonlyField label="CNPJ" value={cedente.documento} /></Cell>
              <Cell span={5}><ReadonlyField label="Razão Social" value={cedente.razaoSocial ?? cedente.nome} /></Cell>
              <Cell span={3}><FormField label="Nome Fantasia" placeholder="—" value={nomeFantasia} onChange={(e) => setNomeFantasia(e.target.value)} /></Cell>

              <Cell span={4}><ReadonlyField label="Data de abertura" value={cedente.dataAbertura} /></Cell>
              <Cell span={4}><FormField label="Tipo" placeholder="—" value={tipoEmpresa} onChange={(e) => setTipoEmpresa(e.target.value)} /></Cell>
              <Cell span={4}><FormField label="Porte" placeholder="—" value={porte} onChange={(e) => setPorte(e.target.value)} /></Cell>

              <Cell span={6}><FormField label="Atividade principal" placeholder="—" value={atividadePrincipal} onChange={(e) => setAtividadePrincipal(e.target.value)} /></Cell>
              <Cell span={6}><FormField label="Natureza Jurídica" placeholder="—" value={naturezaJuridica} onChange={(e) => setNaturezaJuridica(e.target.value)} /></Cell>

              <Cell span={6}><FormField label="Inscrição municipal" placeholder="—" value={inscricaoMunicipal} onChange={(e) => setInscricaoMunicipal(e.target.value)} /></Cell>
              <Cell span={6}><FormField label="Inscrição estadual" placeholder="—" value={inscricaoEstadual} onChange={(e) => setInscricaoEstadual(e.target.value)} /></Cell>
            </div>
          )}
        </div>

        {/* Footer */}
        <div className="flex items-center justify-end" style={{ gap: 12, padding: '16px 28px', borderTop: '1px solid var(--border-default)', flexShrink: 0 }}>
          <button
            onClick={onClose}
            style={{ height: 40, padding: '0 20px', background: 'none', border: 'none', cursor: 'pointer', color: 'var(--text-muted)', fontWeight: 'var(--weight-semibold)', fontSize: 'var(--text-sm)' }}
          >
            Cancelar
          </button>
          <button
            onClick={handleAtualizar}
            style={{ height: 40, padding: '0 24px', border: 'none', borderRadius: 'var(--radius-lg)', cursor: 'pointer', fontWeight: 'var(--weight-bold)', fontSize: 'var(--text-xs)', letterSpacing: '0.08em', background: 'var(--action-primary-bg)', color: '#fff' }}
          >
            ATUALIZAR
          </button>
        </div>
      </div>
    </div>
  );
}
